### ISSUE TITLE
Problem when two versions of the activesupport gem are installed

### ISSUE THREAD

**Issue by javan** [javan/whenever#1]
If two versions are installed, Whenever loads the newer one, and then if you try to use Whenever with a Rails app that requires the older version of the gem, it dies:

<code><pre>
/usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:149:in activate': can't activate activesupport (= 2.1.1, runtime), already activated activesupport-2.3.2 (Gem::Exception)

   from /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:165:in `activate'
   from /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:164:in`each'
   from /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:164:in `activate'
   from /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:49:in`gem'
   from ./config/boot.rb:59:in `load_rails_gem'
   from ./config/boot.rb:53:in`load_initializer'
   from ./config/boot.rb:38:in `run'
   from ./config/boot.rb:11:in`boot!'
    ... 7 levels...
   from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in

require'

   from /usr/local/lib/ruby/gems/1.8/gems/javan-whenever-0.1.7/bin/whenever:7
   from /usr/local/bin/whenever:19:in `load'
   from /usr/local/bin/whenever:19
</pre></code>

**Comment by yanhackcode15** [comment]
I'm on 0.3.7, when running  $bundle exec whenever, I get the following error:
To user Whenever you need the activesupport gem:
$ sudo gem install activesupport

I then install activesupport and tried $bundle exec whenever, again I get the exactly same error

**Comment by javan** [comment]
@yanhackcode15 0.3.7 was released 7 years ago. Consider using a newer version.
