### ISSUE TITLE
whenever with sudo rake script

### ISSUE THREAD

**Issue by chamnap** [javan/whenever#103]
This is not a bug, basically, but I can't figure out how to run a rake task with a root privileged on the whenever gem. Hope you could guide me.
Thanks
Chamnap

**Comment by patakijv** [comment]
Is it possible to have both cases, some jobs installed for the root user and some for app user within the same rails app setup?

**Comment by benlangfeld** [comment]
@patakijv Only if you write your own Capistrano tasks for such a thing, probably using multiple schedule files. You really shouldn't need to run as root, though, and should re-evaluate your approach if you believe that's necessary.

**Comment by patakijv** [comment]
It’s required to be root for some things like monit but not others. Unfortunately we don’t use Capistrano any longer since migrating to docker containers for rails apps, as it’s not needed, but still use whenever to define cron jobs and have both user and root cron jobs.

**Comment by benlangfeld** [comment]
What are you doing with monit inside a Docker container? Why can’t you give your app user access to monit via sudo, rather than actually running the job as root?
