### ISSUE TITLE
Specify day on monthly jobs

### ISSUE THREAD

**Issue by tsommer** [javan/whenever#13]
When i tried to set a time with a monthly cronjob i had to use '1.month'.
But this created a cronjob for every month on todays day, eg.

0 9 18 \* \* ..... instead of
0 9 1 \* \*   ..... which would fire on the first day of the month...

**Comment by jinyi0313** [comment]
how i create every 2 month, end of day(31th), 11 59pm do cron?
every 2.month, at 59 11 L * 0
