### ISSUE TITLE
wheneverize: command not found

### ISSUE THREAD

**Issue by lgs** [javan/whenever#181]
My first try to wheneverize get command not found :

<pre>
lsoave@ubuntu:~/rails/github/gitwatcher.old$ wheneverize .
wheneverize: command not found
</pre>

here it is my conf:

<pre>
lsoave@ubuntu:~/rails/github/gitwatcher.old$ grep whenever Gemfile
gem 'whenever', :require => false

lsoave@ubuntu:~/rails/github/gitwatcher.old$ grep whenever Gemfile.lock
    whenever (0.7.0)
  whenever
lsoave@ubuntu:~/rails/github/gitwatcher.old$ 
</pre>

Luca

**Comment by tmclark737** [comment]
bundle exec wheneverize .

Worked for me!

**Comment by gthomas3** [comment]
Same issue.. 'bundle exec wheneverize .' worked for me
