### ISSUE TITLE
Every block should execute commands as one big command by default

### ISSUE THREAD

**Issue by lukaskonarovsky** [javan/whenever#19]
Reason behind this naturally assuming that task defined in one every block will run in specified order and not all at once. 

For parallel execution should be used just multiple every blocks.

**Comment by taketo1113** [comment]
Support for `sequential` job definitions was added in v1.1.3 (#854).
https://github.com/javan/whenever/releases/tag/v1.1.3

For example:
```ruby
every 2.hours, sequential: true do
  command "blahblah"
  command "foofoo"
end
```

This generates the following crontab entry:

```sh
# crontab
0 0,2,4,6,8,10,12,14,16,18,20,22 * * * /bin/bash -l -c 'blahblah' ; /bin/bash -l -c 'foofoo'
```
