### ISSUE TITLE
Exclude days

### ISSUE THREAD

**Issue by alexbevi** [javan/whenever#314]
Even though we can do this using the raw cron format, it would be nice to be able to use the DSL to do something like

``` ruby
every :day, :except => :sunday, :at => "12:00PM" do
  ...
end

every :day, :except => [:monday, :wednesday], :at => "1:00PM" do
  ...
end
```

**Comment by HLFH** [comment]
I would like to do this:

```
every 1.minute, :except => [:saturday, :sunday] do
  ...
end
```        

@javan Hi. Is that possible to do it with `whenever`?

**Comment by benlangfeld** [comment]
You can use the last example @javan provided here (a whitelist). A blacklist would require a PR.
