### ISSUE TITLE
Single quote escaping broken

### ISSUE THREAD

**Issue by holstvoogd** [javan/whenever#327]
single quotes are replace by '\'', this should be \' if i'm not mistaking.

Let's say we have:
set :job_template, "/usr/bin/bash -lc ':job'"
set :output, {:error => 'cron.log'}
every 1.day, :at => '9am' do
 runner "Task.run"
end

it wil output something like:
0 9 \* \* \* /usr/bin/bash -lc 'script/rails runner -e production '\''Task.run'\'' 2>> cron.log'

So that won't work :) It seems to be line 49 of lib/whenever/job.rb that does this. 

Actually, I'd expect runner "bla" to use double quotes in the output as well.

**Comment by Almaron** [comment]
So is it preferable to use double quotes in runners in schedule.rb?
