### ISSUE TITLE
Cron job not being created when deploying with Capistrano

### ISSUE THREAD

**Issue by gbillingsley** [javan/whenever#331]
I'm having trouble getting whenever to create a cron job when deploying with Capistrano. My configuration is below:

relevant section of deploy.rb:

```
# Initialize RVM
require "rvm/capistrano"
set :rvm_ruby_string, :local
set :rvm_type, :system

# Update gems on deployment
require 'bundler/capistrano'

# Update crontab for scheduled scripts
set :whenever_command, "bundle exec whenever"
require 'whenever/capistrano'
```

relevant output from Capistrano:

```
  * 2013-04-10 16:35:25 executing `whenever:update_crontab'
```

That's it. Just this one line is being output with regards to whenever. There isn't a confirmation or error message after it.

The cron job isn't being created through Capistrano, however, if I run 'bundle exec whenever -w' on the production server, the cron job does get created.

I'm sure it is just some setting that I'm missing, but I can't figure it out.

**Comment by RuslanHamidullin** [comment]
Replaced:
```
server '<IP>', user: 'qae', roles: %w{web app}
```
with:
```
server '<IP>', user: 'qae', roles: %w{web app db}
```
and works fine =)

**Comment by dvodvo** [comment]
Chiming in real late now. @wmene and @gbillingsley are correct: wording is misleading. At the very least, state how roles default to db **before** telling users to *safely* stop reading...
