### ISSUE TITLE
[Solution] RVM: cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by lucasvel** [javan/whenever#393]
I've been strugling the last couple of days with <b>cannot load such file -- bundler/setup (LoadError)</b> in production when tasks were executed by cron.

I couldn't find a solution googling or searching through the issues so here's what worked for me:

My production setup is running RVM and I deploy via capistrano. 
I've installed whenever according to the readme.
My config/schedule.rb ended up like this:

``` ruby
every 3.minutes do
    runner "AppMailer.test.deliver"
end
```

I tried several options in config/schedule.rb like:

``` ruby
env :PATH, ENV['PATH'] # or custom paths
env :GEM_PATH, ENV[GEM_'PATH'] # capistrano shared gems, customs paths
```

but none of them helped.

By running the following command in production the issue was solved:

``` shell
rvm cron setup
```

HTH

**Comment by martyciz** [comment]
Thank you :+1:
