### ISSUE TITLE
Ruby on Rails 4 whenever cron job not working

### ISSUE THREAD

**Issue by robertochingon** [javan/whenever#399]
Hi, 

  i´m trying to use whenver in my rails app, but it´s not working for me. I guess I´m missing something. 

Please see this post for details:

http://stackoverflow.com/questions/20749162/ruby-on-rails-4-whenever-cron-job-not-working

I need help.

Thanks,
Roberto.

**Comment by karthickms** [comment]
HI javan,
How can i set a cron in ubuntu, just i need to send a mail to my members almost 100 people on everyday in my server.
