### ISSUE TITLE
Capistrano bin/rails stub

### ISSUE THREAD

**Issue by RaulKite** [javan/whenever#457]
Hello,

When I try to execute commands in cron, I get this error:

Looks like your app's ./bin/rails is a stub that was generated by Bundler.

In Rails 4, your app's bin/ directory contains executables that are versioned
like any other source code, rather than stubs that are generated on demand.

Here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rake rails:update:bin         # Use the new Rails 4 executables
  git add bin                   # Add bin/ to source control

I also have problems with capistrano deploy as you can see here: 
https://github.com/javan/whenever/issues/431#issuecomment-43485781

Any suggestion?

Thanks

**Comment by ishields** [comment]
Is there anyway to prevent this?  It's kind of making the log files harder to read.
