### ISSUE TITLE
bundle: command not found

### ISSUE THREAD

**Issue by tonytonyjan** [javan/whenever#473]
``` ruby
env :PATH, ENV['PATH']
env :GEM_PATH, ENV['GEM_PATH']
```

I found a lot of issues solved environment problem like `bundle: command not found` using the solutions above.

I don't know why it works. Does it means that `whenever` do not load environment variable by default? `env :FOO, ENV['FOO']` seems not smart, I wonder if such feature can be built in the gem?

**Comment by kostyakch** [comment]
Try adding `env :PATH, ENV['PATH']` to the top of your schedule.rb file.

**Comment by mkosuri** [comment]
@kostyakch working fine thank

**Comment by MakotoTheKnight** [comment]
@mikz I've run into this exact situation, and I'm agreeing that it's not directly the fault of Whenever.  If nothing else, the documentation *should* be improved to point this scenario out, as it does lead one down to a bit of a rabbit hole.

**Comment by endorfin** [comment]
Thanks! @kostyakch

**Comment by zhangzheflying** [comment]
If U want,I think U can edit crontab directly with `crontab -e`.
 See the `$PATH` `,$GEM_PATH` with `echo $PATH`,`echo $GEM_PATH`.

**Comment by IrineuFilho** [comment]
thanks @kostyakch work fine for me too =D

**Comment by maximberdnikov** [comment]
Stumbled upon this issue.

A link for those who'd like to know more about `cron` & environment:  
https://askubuntu.com/a/23438/864469

Also, if you use `rbenv` for managing Ruby env this command may help:  
```
set :bundle_command, '/home/deploy/.rbenv/shims/bundle exec'
```
