### ISSUE TITLE
Setting incorrect cron syntax

### ISSUE THREAD

**Issue by jkbrooks** [javan/whenever#479]
I wrote the following in `schedule.rb`:
`every :year, at: 'July 26th 3:15 pm' do`
  `#task`
`end`

When I did, whenever added a cron job with the following syntax:

`15 15 26 12 * <command>` Notice, the month is Dec instead of July.

**Comment by attilahorvath** [comment]
This PR should fix this: https://github.com/javan/whenever/pull/692.
