### ISSUE TITLE
syntax for roles array

### ISSUE THREAD

**Issue by dvodvo** [javan/whenever#497]
Deployments are failing because of the whenever commands as `SSHKit::Runner::ExecuteError: Exception while executing on host XX.XXX.XX.XXX: can't convert nil into Hash` and thus `Tasks: TOP => whenever:update_crontab` cannot be set.

The documentation covers the first and third commands below, but not the second. `set :whenever_roles` is inserted as a workaround for the `NoMethodError: undefined method 'to_sym' for nil:NilClass` posted in these issues. Various attempts all lead to an identical behaviour at deployment.  
 set :whenever_command, "bundle exec whenever"
 set :whenever_roles, [:db, :app, :web]
 require "whenever/capistrano"

So either the syntax is wrong or I'm missing something else...

**Comment by kevinobama** [comment]
cap aborted!
NoMethodError: undefined method `to_sym' for nil:NilClass
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration/servers/role_filter.rb:25:in `each'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration/servers/role_filter.rb:25:in `flat_map'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration/servers/role_filter.rb:25:in `required'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration/servers/role_filter.rb:15:in `roles'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration/servers/role_filter.rb:11:in `for'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration/servers.rb:42:in `fetch_roles'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration/servers.rb:19:in `roles_for'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/configuration.rb:53:in `roles_for'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/dsl/env.rb:43:in `roles'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/whenever-0.9.4/lib/whenever/tasks/whenever.rake:5:in `setup_whenever_task'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/whenever-0.9.4/lib/whenever/tasks/whenever.rake:17:in `block (2 levels) in <top (required)>'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/dsl/task_enhancements.rb:12:in `block in after'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/dsl.rb:14:in `invoke'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/tasks/framework.rake:64:in `each'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/tasks/framework.rake:64:in `block in <top (required)>'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/lib/capistrano/application.rb:15:in `run'
/home/barackobama/.rvm/gems/ruby-2.1.5/gems/capistrano-3.1.0/bin/cap:3:in `<top (required)>'
/home/barackobama/.rvm/gems/ruby-2.1.5/bin/cap:23:in `load'
/home/barackobama/.rvm/gems/ruby-2.1.5/bin/cap:23:in `<main>'
/home/barackobama/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/barackobama/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => whenever:update_crontab
(See full trace by running task with --trace)
The deploy has failed with an error: #<NoMethodError: undefined method `to_sym' for nil:NilClass>
