### ISSUE TITLE
Cron raises error "/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)"

### ISSUE THREAD

**Issue by sekouzed** [javan/whenever#508]
hi, please i need help!
when i running Cron job  using whenever 
i have this error in my file cron_error_log.log :
 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/sekouzed/Bureau/rails/diaryApp/config/boot.rb:3:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'

my shedule.rb is:

set :environment, "development"
set :output, {:error => "cron_error_log.log", :standard => "cron_log.log"}
env :PATH, '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/lib'
every 1.minute do
  runner "Event.update_state_to_expire"
end

 if i run the entire command manually (without logging):
/bin/bash -l -c 'cd [my app full directory] && bin/rails runner -e development '\''Event.update_state_to_expire'\'''"
that'a work all right

**Comment by maxigarciaf** [comment]
I'm having the same issue, have you fixed it?

**Comment by lorenzosinisi** [comment]
I've solved, read my comment here: https://github.com/javan/whenever/issues/559

**Comment by benlangfeld** [comment]
This was fixed by https://github.com/javan/whenever/commit/9f3707615c654bd21211ca164ddc938eca3cba76
