### ISSUE TITLE
job_type itself shouldn't be parsed

### ISSUE THREAD

**Issue by iCEAGE** [javan/whenever#520]
Hi,
I have a rake task in schedule.rb like below:
````rb
every 3.minutes do
  rake "db:update_something[4.minutes.ago.utc]"
end
````
The problem is whenever parse rake task itself and the result would be something like:
````sh
0 0 * * * /bin/bash -l -c 'cd /my_project && RAILS_ENV=production bundle exec rake db:update_something[240.ago.utc] --silent'
````
which is incorrect. Is this expected behaviour to parse "db:update_something[4.minutes.ago.utc]" into 
"db:update_something[240.ago.utc]"? becuase "[4.minutes.ago.utc]" is the parameter of the rake task and I don't want to be parsed.

FYI:
I'm using ruby 2.2.0, whenver 0.9.4 and chronic 0.10.2.

**Comment by paulmenzel** [comment]
Hi. I experience the same problem. Sorry for not being more helpful.

**Comment by robvolk** [comment]
bump.  facing the same issue : /

**Comment by robvolk** [comment]
I found a workaround @iCEAGE, just add `#{4}.minutes.aog' - crazy I know.

```ruby
every 3.minutes do
  rake "db:update_something[#{4}.minutes.ago.utc]"
end
```

**Comment by iCEAGE** [comment]
@robvolk Thanks, good one and it works!

**Comment by benlangfeld** [comment]
Per @javan, we'll need to avoid parsing Ruby code inside quotes: https://github.com/javan/whenever/issues/530#issuecomment-71270254

**Comment by benlangfeld** [comment]
This is fixed by This was fixed by https://github.com/javan/whenever/pull/587.
