### ISSUE TITLE
Can I stop when failed

### ISSUE THREAD

**Issue by arthurtalkgoal** [javan/whenever#526]
I have a task running every 5 minutes to send scheduled emails.

I found that it will fork a list of process when I deployed via Capistrano as the app is overloading the server.

Can I either stop the whenever task when it failed or pause it during capistrano deploy?

Thanks,

**Comment by javan** [comment]
You could run `whenever:clear_crontab` early in your deploy to prevent any new jobs from running _during_ your deploy, but beyond that it would be a matter of finding running processes and terminating them using some kind of unix script.

Using [nice](http://en.wikipedia.org/wiki/Nice_%28Unix%29) might help you keep your cron jobs from consuming too many resources.
