### ISSUE TITLE
Unscheduling jobs at runtime

### ISSUE THREAD

**Issue by acajic** [javan/whenever#528]
Excuse me if I've overlooked this information somewhere on this site. 

I am trying to find out whether Whenever supports scheduling and unscheduling jobs at runtime. 

This means that the app reponds to the user request and starts a cron job. After a while (couple of days later) the app responds to another request and stops the same cron job that it started.

I don't see that the sheduled job is saved anywhere or that it was given an ID or a tag... 

If I could give it a tag, then I could say: 
"Find all cron jobs with this tag an unschedule them from executing ever again."

**Comment by rosswilson** [comment]
Rather than adding and removing cron jobs on the fly, I'd have a single cron job that runs a script under your control (like a rake task). Then have *that* task query the database to work out what scripts it should run.

**Comment by acajic** [comment]
For example a Web App where users create games. Every game lasts several days. Depening on when the game started and how it's set up, the game must perform some work (some calculations and generation of data in DB) at specific moments in time even when none of the players are online.

When the game is ended and deleted, its scheduled jobs should be deleted.
This is because any new games that get created will have scheduled jobs at potentially very different time of day.

**Comment by rosswilson** [comment]
Yep, so your script would be set to run every 10 minutes (for example), query the database to see what games are currently active, and then run any tasks that need to be run for each game.

**Comment by acajic** [comment]
But this would not be sufficient.

It would be preferable that the scheduled job gets executed to 1 second precision.

And to set that a script gets executed every second would imply massive processing overhead.

**Comment by rosswilson** [comment]
You'll only get to 1 minute regularity with Cron anyway. I think you should
revisit why you need this process to run so frequently and at such
precision. Can't you batch up your actions?

Does this even need to be a scheduled task? Can't the game calculate at
runtime what the correct state should be based on its knowledge of what
"pseudo-scheduled" tasks would've done?

**Comment by benlangfeld** [comment]
I don't think this is within the remit of Whenever or indeed cron. I'm going to close this, but feel free to continue any discussion here :)
