### ISSUE TITLE
Seconds considered as days

### ISSUE THREAD

**Issue by andreasantillana** [javan/whenever#530]
Starting with version 0.9.3, things like `1.day` are being converted to `86400`, and when Rails receives and integer, it's considered as days.

```
1.9.3-p484 :002 > DateTime.now - 86400
 => Sat, 04 Jul 1778 12:02:51 -0600 
1.9.3-p484 :003 > DateTime.now - 86400.day
 => Sat, 04 Jul 1778 12:02:59 -0600 
1.9.3-p484 :004 > DateTime.now - 86400.seconds
 => Thu, 22 Jan 2015 12:03:02 -0600 
```

**Comment by javan** [comment]
Whenever's numeric time/date extensions are not the same as those in Rails so their behavior may differ slightly. Is this causing an issue with your usage of Whenever?

**Comment by andreasantillana** [comment]
Yes, I had to downgrade to version 0.9.2 because models were created with the wrong date (1778)

**Comment by javan** [comment]
Can you paste a sample from your schedule.rb file?

**Comment by andreasantillana** [comment]
```
every 1.day, :at => '5:00 am' do
  runner 'method(DateTime.now - 1.day, true)'
end
```

as I wrote before, `1.day` turns into `86400` seconds, and then it's considered as 86400 days.

**Comment by javan** [comment]
Thanks. #520 is related. A fix might be for Whenever to skip parsing numeric time extensions inside of quotes or perhaps only parse them after the `every` statement. I'll think on it.

**Comment by andreasantillana** [comment]
Thanks :smile:

**Comment by benlangfeld** [comment]
I'm closing this because it's more precisely defined in #520. Please follow that issue for a resolution.
