### ISSUE TITLE
Feature request: Set default shell to zsh

### ISSUE THREAD

**Issue by dt1973** [javan/whenever#532]
Would it be possible to set the default shell to zsh? It allows you to write way more beautiful and potent shell code. In addition:

http://en.wikipedia.org/wiki/Shellshock_(software_bug)

**Comment by javan** [comment]
Check the README section on setting your own `:job_template`.

**Comment by dt1973** [comment]
Yep, I noticed. Would be nice if bash was no longer the default though.
