### ISSUE TITLE
Unable to access Ruby from cron: command not found: ruby

### ISSUE THREAD

**Issue by dt1973** [javan/whenever#533]
How come I can't access Ruby from cron? Getting emails like:

    Subject: Cron <dt1973@mybox>
    /usr/local/bin/zsh -l -c 'ruby -v': zsh:1: command not found: ruby`

I tried to simulate the cron environment with `env -i /usr/local/bin/zsh --no-rcs` but there Ruby runs just fine. Getting the same with bash.

**Comment by javan** [comment]
Are you using a Ruby version manager like RVM? Perhaps it isn't initialized correctly in cron's limited environment. Regardless of the answer, this isn't a Whenever issue.

**Comment by dt1973** [comment]
> Are you using a Ruby version manager like RVM?

Nope, I just "vanilla" Ruby. I didn't have this problem on my old server running RVM though.

> Perhaps it isn't initialized correctly in cron's limited environment.

According to http://stackoverflow.com/questions/20954298/gem-not-found-in-ruby-cron-job-in-rvm-env I have to manually reinitialize my env variables in my crontab file after Whenever has generated it. There's gotta be a better way though?

> Regardless of the answer, this isn't a Whenever issue.

Sorry about that.

**Comment by dt1973** [comment]
I just had to export the proper PATH:

```
job_type :rake, "export PATH=/usr/local/bin && cd :path && :environment_variable=:environment /usr/local/bin/bundle exec rake :task --silent :output"
```

Many thanks!
