### ISSUE TITLE
/bin/bash: bundle: command not found

### ISSUE THREAD

**Issue by Manju244** [javan/whenever#542]
This is the code i have written in schedule.rb

``` ruby
every 2.minutes do
   rake "task_overdue:overdue" 
end
```

But after 2 minutes i am getting error  `/bin/bash: bundle: command not found` in cron.log file

Using Rails4 with latest whenever gem.

Tried to fix it but giving the same error.

**Comment by michaelachrisco** [comment]
I have the same issue. The crontab listed command can be run manually just fine and shows up in the log file.

**Comment by michaelachrisco** [comment]
Looks like it was an old error:
https://groups.google.com/forum/#!msg/whenever-gem/yRLt3f2jrfU/Exu3xfCo8DAJ
Setting the PATH seems to do the trick with:
```Ruby
env :PATH, ENV['PATH']
```

**Comment by ajsharp** [comment]
This seems like a reasonable default that whenever should include in the config file automatically.

**Comment by karthickms** [comment]
Also trying following 2 line in schedule.rb

env :PATH, ENV['PATH']
env :GEM_PATH, ENV['GEM_PATH']

**Comment by brunoban** [comment]
I could not get any of them to work for the life of me.

My gem env:

RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/bundle
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/bundle
     - /root/.gem/ruby/2.2.0
     - /usr/local/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bundle/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin


My $PATH

`/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

And my bundle show --paths is listing bundler as being in:

`/usr/local/bundle/gems/bundler-1.10.5`

I'm using a docker container from the rails:4.2.3 image with my app and cron installed. I'm not using rbenv or rvm.

Any ideas?

**Comment by inyerade** [comment]
I have similar problem, I use

    env :PATH, ENV['PATH']
    env :GEM_PATH, ENV['GEM_PATH']
    env :GEM_HOME, ENV['GEM_HOME']

and nothing.

in my .bashrc I add

    source "$HOME/.rvm/scripts/rvm"

also nothing. But when I login to my server and run the task I do not have problems

I solve my problem with this code

    rvm cron setup

And delete all `env` set

    env :PATH, ENV['PATH']
    env :GEM_PATH, ENV['GEM_PATH']
    env :GEM_HOME, ENV['GEM_HOME']

**Comment by yjchieng** [comment]
env :PATH, ENV['PATH'] solved my issue.

env :GEM_PATH, ENV['GEM_PATH'] creates more error in my case:

`/home/ubuntu/.rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 6 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=', execute `gem env` for more information
	from /home/ubuntu/.rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /home/ubuntu/.rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/ubuntu/.rbenv/versions/2.2.5/bin/bundle:22:in `<main>'`

**Comment by dvodvo** [comment]
[comment is tangential to problema at hand, but may be useful for someone stumbling upon this]
I second yjchieng's observation.  I would add that [askrynnikov's comment](https://github.com/javan/whenever/issues/486) was also needed for me to get a whenever taks to run properly, as rbenv was not being found as well.

**Comment by austinarchibald** [comment]
`env :PATH, ENV['PATH']` at the top of my `schedule.rb` also solved it. I tried many other things. Using rbenv, capistrano, rails 5, and whenever gem.

**Comment by gregblass** [comment]
@austinarchibald's comment worked for me, finally. There should really be a mention of this on the wiki page for RBENV users.

**Comment by bekkou68** [comment]
> `env :PATH, ENV['PATH']` at the top of my `schedule.rb` also solved it. I tried many other things. Using rbenv, capistrano, rails 5, and whenever gem.

Thanks. I also solved the same problem by adding `env :PATH, ENV['PATH']` at the top of my `schedule.rb`.

FYI, by adding it, whenever generates cron like below:

```
PATH=/home/deploy/.rbenv/versions/3.1.2/bin:/home/deploy/.rbenv/libexec:...

0,0 0 * * * /bin/bash -l -c 'cd /var/www/myapp/releases/yyyymmdd && RAILS_ENV=production bundle exec ...

...
```

My environment is whenever 1.0.0, Rails 7.0.3.1, Ruby 3.1.2, and capistrano 3.17.1.
