### ISSUE TITLE
/bin/bash: p: command not found

### ISSUE THREAD

**Issue by madhusudhan518** [javan/whenever#545]
my schedule.rb file contains below code

```ruby
every 1.minute do
 command "p 'check command' "
end
```

when ever i try to update using `bundle exec whenever --set environment=production  --update-crontab store` it is updating well.

when the time come to run , i am getting error 

```
/bin/bash: p: command not found
```

can any one tell me why it's wrong ?
one more important thing my rails production server don't have rvm installed in it.

```ruby
set :whenever_command, "bundle exec whenever"
set :whenever_identifier, "deployer"
set :whenever_roles,        ->{ [:remind_unaccepted_bookings,:remind_going_to_expire_meetings,:db,:app] }
set :whenever_options,      ->{ {:roles => fetch(:whenever_roles)} }
set :whenever_environment,  ->{ fetch :rails_env, "production" }
set :whenever_variables,    ->{ "environment=#{fetch :whenever_environment}" }
set :whenever_update_flags, ->{ "--update-crontab #{fetch :whenever_identifier} --set #{fetch :whenever_variables}" }
set :whenever_clear_flags,  ->{ "--clear-crontab #{fetch :whenever_identifier}" }
require "whenever/capistrano"
```

**Comment by rud** [comment]
I think the "command" is a shell-command. What you have written is ruby-code. Maybe replace `p` with `echo`?

**Comment by madhusudhan518** [comment]
Thanks for the reply @rud . i am checking.

**Comment by benlangfeld** [comment]
@rud is indeed correct here. If you want to execute Ruby code, use `runner`.
