### ISSUE TITLE
Loading environment variables

### ISSUE THREAD

**Issue by nzaillian** [javan/whenever#546]
Is there any way to pull in variables defined in ~/.profile, ~/.app_vars (or any dotfile for that matter) to have rake tasks run in the context of when we've set them up using whenever? In our production deployment we have certain environment variables essential for our app's functioning set in a dotfile in the deploy user's home directory, outside of the repository/staging directory. Can you let me know what the easiest way to make sure that these are exposed in ENV for our app when it is run by cron. Basically I am looking for a way to have cron "source ~/.thedotfile" to get the environment vars defined locally on the server in context when it runs the rake task. Thanks!

**Comment by nzaillian** [comment]
I wanted to update this to say that I came up with a solution that works at the application level. If there is a way that it makes sense to do this at the level of whenever feel free to let me know but I wanted to just add to this thread that the following initializer is working for me to grab my env vars from a yaml file of my specification:

```
Rails.application.config.before_configuration do
  home_dir = File.expand_path('~')

  app_env_var_file_path = "#{home_dir}/.app_vars.yml"

  if File.exists?(app_env_var_file_path)
    contents = File.read(app_env_var_file_path)

    values = YAML::load(contents)

    values.each_pair do |key, val|
      ENV[key.to_s] = val
    end
  end
end
```

Hope that helps. Feel free to close this if you don't have a "whenever"-level solution to share. Thanks!

**Comment by benlangfeld** [comment]
Thanks for clarifying @nzaillian! I think this is something that should be deferred either directly to the application to load its own configuration file or via some generic solution like `dotenv` or `foreman`. I don't think we need a Whenever-specific solution to loading application config.
