### ISSUE TITLE
Log rotation support?

### ISSUE THREAD

**Issue by fabrouy** [javan/whenever#551]
Hi! First of all thanks for building up this awesome gem, I am using it a lot. Second, I don't know If this is the right place to make sugestions, If not please let me know where.

I could not find a way to use a customer logger. I would like to do something like this inside a block:

```ruby
config.logger = Logger.new(Rails.root.join("log", "cron.error.log"), "daily")
```

Is it possible or maybe could it be considered a future feature?

Thank you!

**Comment by benlangfeld** [comment]
You can use [output redirection](https://github.com/javan/whenever/wiki/Output-redirection-aka-logging-your-cron-jobs) to choose a log file. You can then use logrotate to rotate the file.
