### ISSUE TITLE
Gemfile not found when running Cron job with Capistrano 3 and whenever gem

### ISSUE THREAD

**Issue by jianbo** [javan/whenever#555]
My cron job works fine on my local machine after running `whenever -w`, after deploy to my VPS, I get this error, `release 20150415044915 doesn't exist`. any idea?

I looked at my crontab -e, the path also looks fine where 20150502114703 is the correct release:

    0 1 * * 1 /bin/bash -l -c 'cd /home/hey_production/releases/20150502114703 && bin/rails runner ....

Error Log:

    /usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.7.3/lib/bundler/definition.rb:22:in `build': /home/hey_production/releases/20150415044915/Gemfile not found (Bundler::GemfileNotFound)
	  from /usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.7.3/lib/bundler.rb:154:in `definition'
	  from /usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.7.3/lib/bundler.rb:117:in `setup'
  	  from /usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.7.3/lib/bundler/setup.rb:17:in `<top (required)>'
	  from /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	  from /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	  from /usr/local/rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	  from bin/rails:14:in `<main>'

**Comment by jianbo** [comment]
How do I setup BUNDLE_GEMFILE in my schedule.rb file?

**Comment by superbilk** [comment]
I have a similar issue since two weeks (started around May, 11th). And maybe a *fix* at the end of my comment.

That's one line in my crontab:

    7 0 * * * /bin/bash -l -c 'cd /home/christian/apps/happinessmetric/releases/20150526195213 && bin/rails runner -e production '\''SystemMailer.delay.statistics'\'''

And if I run it in a shell:

    /bin/bash -l -c 'cd /home/christian/apps/happinessmetric/releases/20150526195213 && bin/rails runner -e production '\''SystemMailer.delay.statistics'\'''

I get an error:

    /home/christian/apps/happinessmetric/releases/20141222191928/Gemfile not found

The Gemfile is there, the timestamp is my current release.

So I tried to add  `bundle exec` to bin/rails runner:

    /bin/bash -l -c 'cd /home/christian/apps/happinessmetric/releases/20150526195213 && bundle exec bin/rails runner -e production '\''SystemMailer.delay.statistics'\'''

And it works (with the usual complaining from Bundler about bin stubs

    Looks like your app's ./bin/rails is a stub that was generated by Bundler.

And the *fix* is: customize your job_type, I added this line on top of my `config/schedule.rb`

    job_type :runner,  "cd :path && bundle exec bin/rails runner -e :environment ':task' :output"

I have no idea why it broke two weeks ago, but now it's working for me.

**Comment by superbilk** [comment]
Also have a look into that issue:
https://github.com/capistrano/bundler/issues/45

I also followed this advice:
https://github.com/capistrano/bundler/issues/45#issuecomment-47428203

**Comment by Silox** [comment]
:+1: same problem, fixed it using the `job_type` modifier

**Comment by benlangfeld** [comment]
This should have been fixed by https://github.com/javan/whenever/commit/9f3707615c654bd21211ca164ddc938eca3cba76
