### ISSUE TITLE
using whenever/capistrano only for production stage

### ISSUE THREAD

**Issue by karlingen** [javan/whenever#563]
My production and staging environments are on the same machine. 
I'm guessing that putting `set :whenever_identifier, ->{ "#{fetch(:application)}_#{fetch(:stage)}" }` inside `config/deploy.rb` will update the crontab for both environments.

Running Capistrano V3 with the following inside `schedule.rb`:
```
# Sending out reminders
every 10.minutes do
  runner "Tasks::Notifications::Email::Reminder.new.perform"
end
```

Is it possible to tell `whenever/capistrano` to only update the crontab for production and not staging environment?

**Comment by karlingen** [comment]
Found this instead: https://groups.google.com/forum/#!topic/whenever-gem/weOGOaMCjj8

**Comment by kjakub** [comment]
Having same question. I tried something like Rails.env.staging? in schedule.rb, but that is not working

**Comment by poblahblahblah** [comment]
Here is how we take care of this:

in `config/deploy/production.rb`:

```
role :production_cron, %w{foo1.colo.goldstar.com}
```

in `config/deploy.rb`:
```
set :whenever_roles, "#{fetch(:rails_env)}_cron"
```

in `config/schedule.rb`:
```
every :day, at: '1:00am', roles: :production_cron do
  runner "Report.send_daily_usage_report"
end
```

**Comment by kjakub** [comment]
thank you, this can be closed

**Comment by germanotm** [comment]
I think i solved this in a simpler way. I override the whenever update task only in staging enviroment.

Just put this line on deploy/stagind.rb

    Rake::Task["whenever:update_crontab"].clear_actions

Found the solution here: http://capistranorb.com/documentation/advanced-features/overriding-capistrano-tasks/
