### ISSUE TITLE
Rails logger to stdout

### ISSUE THREAD

**Issue by naps62** [javan/whenever#564]
I want my whenever jobs to also output Rails logger messages to log/whenever.log. I know by default, STDOUT is redirected, which allows me to use `puts "message"`. But what I really want is to be able to do `Rails.logger.info "message"

What I'm doing right now is this:

``` ruby
# config/schedule.rb

env 'WHENEVER', true
```

``` ruby
# config/initializers/0_logging.rb

if ENV['WHENEVER']
  Rails.logger = Logger.new(Rails.root.join('log', 'whenever.log'))
end
```

Notice that I have to name the initializer `0_logging.rb` to make sure it is loaded first. This is because, in other initializers, I'm redirecting other loggers to the Rails logger (I'm using some other gems which also have their own loggers), so it has to already be set by then.
So I was wondering if there was a more sane way to do this?

I would think this is a common requirement, but I couldn't find anything on this

**Comment by rafaltrojanowski** [comment]
+1

**Comment by itsprdp** [comment]
+1

**Comment by lgcjwt** [comment]
+1

**Comment by pioz** [comment]
With Rails 5+ you can use the env variable `RAILS_LOG_TO_STDOUT` (view your `config/environments/production.rb` for example) to redirect Rails logger to STDOUT. So the only thing that you have to do is to add the line `env 'RAILS_LOG_TO_STDOUT', true` in your `config/schedule.rb`
