### ISSUE TITLE
Whenever can't find a JavaScript runtime. But I have nodejs installed

### ISSUE THREAD

**Issue by THPubs** [javan/whenever#565]
I have Nodejs installed using NVM and have added it to the path. Here's my schedule.rb :

    job_type :rbenv_rake, %Q{export PATH=/usr/local/heroku/bin:/home/pubudu/.nvm/versions/node/v0.12.4/bin:/home/pubudu/.rbenv/plugins/ruby-build/bin:/home/pubudu/.rbenv/shims:/home/pubudu/.rbenv/bin:/home/pubudu/.rbenv/shims:/home/pubudu/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$PATH; eval "$(rbenv init -)"; \
                             cd :path && bin/rails runner -e :environment ':task' :output }

    # Learn more: http://github.com/javan/whenever
    every 1.minutes do
        rbenv_rake 'OrphanRemoveWorker.perform_async'
    end

But when running it gives me this error :

	/home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs/runtimes.rb:48:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs.rb:5:in `<module:ExecJS>'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs.rb:4:in `<top (required)>'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/uglifier-2.7.1/lib/uglifier.rb:3:in `require'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/uglifier-2.7.1/lib/uglifier.rb:3:in `<top (required)>'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:76:in `require'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:72:in `each'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:72:in `block in require'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:61:in `each'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:61:in `require'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.4/lib/bundler.rb:134:in `require'
		from /home/pubudu/Projects/kahawanu/config/application.rb:7:in `<top (required)>'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `require'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `preload'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from /home/pubudu/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
		from -e:1:in `<main>'

What might be the problem?

**Comment by benlangfeld** [comment]
Does this code work when you execute it at a Rails console?

**Comment by THPubs** [comment]
@benlangfeld Very sorry I can't test it now because i'm not using Rails anymore.
