### ISSUE TITLE
Send mail to a user every day

### ISSUE THREAD

**Issue by MarcoDias7** [javan/whenever#570]
Hi,

I've been trying to make this work, but I'm not sure if I'm doing it right.

Here is my schedule.rb :
```
every :day, :at => '12pm' do # Use any day of the week or :weekend, :weekday
  runner "UserMailer.daily_mail"
end
```
My UserMailer :
```
def daily_mail(user)
    @user = user
    mail to: user.email, subject: "Mail journalier"
  end
```
And in my user.rb :
```
# Sends daily email.
  def send_daily_mail
    UserMailer.daily_mail(self).deliver
  end
```

The thing is, I already have mail activation in my project, which is working (I can test it in heroku). The app sends a mail on creation of an account, so in UserController, there is :
```
def create
      @user = User.new(user_params)
      if @user.save
        @user.send_activation_email
        flash[:info] = "Veuillez contrôler votre boîte mail pour activer votre compte."
        redirect_to root_url
      else
        render 'new'
      end
    end
```

But here, it sends an email after an action. But If I want the mail to be sent with whenever, what is left to do to make it work, and how can I test it since I'm not in production (and I think whenever doesn't work with heroku) ?

The endgame would be to have a checkbox in the user preferences, and he would be able to check daily, weekly or monthly updates, and the mails would be sent accordingly.

Thanks

**Comment by joassouza** [comment]
I don't know if I understand your problem. Anyway, if your doubt it's about to send an email without "an action" in the controller you've an easy solution. First of all, you can test in development easily, it works in the same way as production. You only need to set the environments variables.  
Second issue...use whenever without a controller action.
Create a service, task, etc...
In the example I created a service, which is a simple PORO
```ruby
class SendBirthdayMessage
  def initialize
    @users = User.all
  end

  def call
    @users.each do |user|
      contacts_birthday_today = contacts_birthday(user) 
# user.bday_msg? show if the user wants to send message in the birthday
      if user.bday_msg? && contacts_birthday_today
        notification = user.notifications.new(" bla, bla, bla")
        if notification.save
#SendMessage.new("").call is the class responsible for send messages
          SendMessage.new(user, notification).call
        end 
      end
    end
  end

  private
    def contacts_birthday user
      "returns all contacts who the birthday is today"
end

```

Now you only need create the schedule properly in my example

```
set :environment, "development"
env :PATH, ENV['PATH']

set :output, {:error => "log/cron_error_log.log", :standard => "log/cron_log.log"}

every 1.day, :at => '11:23 am'  do
  runner "SendBirthdayMessage.new().call"
end
```
I hope I make myself clear =)

**Comment by swapnilchincholkar** [comment]
@MarcoDias7 

I doubt, is your code working? Probably it should throw an error.

Your function "daily_mail" is accepting user object as an argument but in your schedule.rb, you are calling the method wrong way.

So code could be in this way, please modify & use as needed.

UserMailer looks fine to me.

You need a function to fetch & pass specific/all users to mailer. 
So as @joassouza said, its better to create a task or service. For time being I will write it in model itself.
```ruby
# Loop over users & send daily email to them
def self.send_daily_email_to_all_users
  User.each do |usr|
    UserMailer.daily_mail(usr).deliver
  end
end
```

Your schedule.rb should call method which will pass the users to mailer & not to mailer itself.
```ruby
every :day, :at => '12pm' do # Use any day of the week or :weekend, :weekday
  runner "User.send_daily_email_to_all_users"
end
```

For testing, initially refer to [crontab info](http://www.computerhope.com/unix/ucrontab.htm) .
You can use commands "crontab -l" to list the jobs, "crontab -r" to remove & "crontab -e" to edit em.

Bad new is, making cron jobs to work with heroku will be a nightmare, so simpler solution is either move out of heroku OR to use [scheduler add on](https://devcenter.heroku.com/articles/scheduler).

If you choose to stay on with heroku, after enabling scheduler add on, in its config call a task or service of yours &  you can easily specify the duration at which it should run & thats it.
