### ISSUE TITLE
Forward slashes in schedule.rb are removed in crontab

### ISSUE THREAD

**Issue by robyedlin** [javan/whenever#571]
I have a scheduled task

```ruby
every 15.minutes do 
    command "find #{path}/public/uploads -type f -mmin +10 -exec rm -rf {} \;"
end
```
and when it goes to the crontab, the forward slash before the end of the line is removed

```bash
0,15,30,45 * * * * /bin/bash -l -c 'find /path/to/public/uploads -type f -mmin +10 -exec rm -rf {} ;'
```

Is that a feature or a bug?

**Comment by javan** [comment]
This isn't a Whenever issue. With double quotes, the backslash is escapes the proceeding character. So if you want a literal backslash you'll need to escape it with another backslash.

```ruby
>> puts "\;"
;

>> puts "\\;"
\;
```

https://en.wikibooks.org/wiki/Ruby_Programming/Strings#Double_quotes

**Comment by robyedlin** [comment]
Awesome, thanks. Sorry, I'm a rails noob.
