### ISSUE TITLE
Cannot stagger times

### ISSUE THREAD

**Issue by malakai97** [javan/whenever#572]
I want to run a job every 5 minutes, starting at 12:01am.  I.e. it'll run at 12:01, 12:06, 12:11, etc.

One could assume this to be the correct code:

``` ruby
every 5.minutes, at: '12:01am' do
  runner "puts 'it works'"
end
```

However, an exception is thrown: 

```
<projectdir>/.bundle/ruby/2.2.0/gems/whenever-0.9.4/lib/whenever/cron.rb:143:in `comma_separated_timing': bad value for range (ArgumentError)
```

I think this use case is pretty common.

**Comment by malakai97** [comment]
Currently, I am able to get around this via the following, but it's unintuitive and does not work for more complicated cases:

```ruby
  every :hour, at: (0..60).step(5).to_a.join(",").to_sym do
    runner "zomg"
  end
```

**Comment by swapnilchincholkar** [comment]
```every 5.minutes, at: '12:01am' do``` means this will run on every 5 minutes for all 24 hours so its equivalent to 
```every 5.minutes```, just you want to begin it at 12.01 am, right?

Can you try below code, if running task on every 5 minutes will suffice?

```
every "*/5 * * * * " do
  rake test
end
```

**Comment by malakai97** [comment]
I'm not sure I understand your questions, so I'll try to explain differently.   Imagine you had two tasks foo.sh and bar.sh that each produce heavy load.  You might not want them to run at the same time, so you'd schedule them to run at:

    foo.sh 12:00 12:05 12:10 12:15 etc
    bar.sh 12:02 12:07 12:12 12:17 etc

Thus, both foo.sh and bar.sh run in five minute intervals, but those intervals are staggered from each other.  One would likely expect this to be achieved via:

```ruby
every 5.minutes, at: '12:00am' { command "/path/to/foo.sh" }
every 5.minutes, at: '12:02am' { command "path/to/bar.sh" }
```

The code `every "*/5 * * * * "` won't achieve what I'm looking for in this issue.

**Comment by prasadsurase** [comment]
@malakai97 As far I know, this isn't supported by crontab. Crontab accepts Minute(0-59), Hour(0-23), Day of Month(1-31), Month(1-12 or Jan-Dec), Day of Week(0-6 or Sun-Sat) and Command to be executed in the same order. We can't specify the combination of minutes & hour in the cron job
eg
```sh
    13:16,13:33,13:50 * * * * /run/some/command
```
Now, if you want to run a job which starts at a specific time(say, 12:02 pm) and runs at a fixed time interval(say, every 5 minutes), then this might be achieved by a rails background job(sidekiq, delayed job ...). Each job runs after a fixed interval and updates the crontab. I haven't tried this but this is something that you can try.

**Comment by malakai97** [comment]
Won't cron at least support this:

```
0,5,10,15,20,25,30,35,40,45,50,55 * * * * /foo.sh
2,7,12,17,22,27,32,37,42,47,52,57 * * * * /bar.sh
```

**Comment by prasadsurase** [comment]
@malakai97 It will. In the below case, we want foo.sh to run every 5 minutes.

```ruby
0,5,10,15,20,25,30,35,40,45,50,55 * * * * /foo.sh

# whenever script
every "*/5 * * * * " do
  #run foo.sh
end

OR

every 5.minutes do
  #run foo.sh
end
```

But, we can't run the same script at fixed intervals(say, after every 5 minutes) with it starting at a fixed time(say, 14:02am).

**Comment by malakai97** [comment]
I used the fixed start time as a workaround to attempt to stagger times.  What I really want is to generate what your last `every` example would generate without having to enumerate all of the times or use my `step` workaround.

**Comment by attilahorvath** [comment]
It seems this functionality has been added in the meantime.

You can add an `at` parameter to your job descriptions and they will start from the specified minute. Pay attention though, Whenever expects this to be a single integer, so `'12:01am'` or `10.minutes` or similar will not work.

For example something like:

```ruby
every 5.minutes, at: 1 do
  # run foo.sh
end
```

Will generate:

```
1,6,11,16,21,26,31,36,41,46,51,56 * * * * /foo.sh
```

You can use this to spread your jobs around over time.
