### ISSUE TITLE
Improvement: append to crontab

### ISSUE THREAD

**Issue by txapelgorri** [javan/whenever#575]
Scenario: one server with different projects on it. Each project uses Whenever.

Desired command: cd project_1_path && whenever -w && cd project_2_path && whenever -w --append 
This command would append more cron jobs to the block controlled by Whenver.

I think the main change would be at command_line.rb (around line 100), besides more little changes.

**Comment by benlangfeld** [comment]
This is already implemented. You can pass an identifier to `whenever --update-crontab` to separate sections of the crontab, like `whenever --update-crontab project1`. In Capistrano, this is exposed as the `:whenever_identifier` variable.
