### ISSUE TITLE
crontab not updated on windows

### ISSUE THREAD

**Issue by Sri-K** [javan/whenever#578]
Hi, I installed the whenever gem to my jruby rails application,

```
Gemfile:
gem 'whenever', require: false
```

Schedule.rb
```
set :output, "#{path}/log/cron.log"
set :environment, 'development'

every 1.minute do
  command "echo 'you can use raw cron syntax too'", environment => "development"
end
```
on the gitbash terminal(windows)

I tried, 
```
jruby -S whenever
```
* * * * * /bin/bash -l -c 'echo '\''you can use raw cron syntax too'\'' >> C:/Users/Sriganeshk/Documents/Promaster4Rails/log/cron.log 2>&1'

'## [message] Above is your schedule file converted to cron syntax; your crontab file was not updated.
'##' [message] Run `whenever --help' for more options.

```
whenever --update-crontab or whenever -i
```
IOError: Cannot run program "crontab" (in directory "C:\Users\Sriganeshk\Documents\Promaster4Rails"): CreateProcess error=2, The system cannot find the file specified
          popen at org/jruby/RubyIO.java:4344
  write_crontab at C:/jruby-1.7.15/lib/ruby/gems/shared/gems/whenever-0.9.4/lib/whenever/command_line.rb:72
            run at C:/jruby-1.7.15/lib/ruby/gems/shared/gems/whenever-0.9.4/lib/whenever/command_line.rb:35
        execute at C:/jruby-1.7.15/lib/ruby/gems/shared/gems/whenever-0.9.4/lib/whenever/command_line.rb:6
         (root) at C:/jruby-1.7.15/lib/ruby/gems/shared/gems/whenever-0.9.4/bin/whenever:41
           load at org/jruby/RubyKernel.java:1081
         (root) at C:/jruby-1.7.15/bin/whenever:23

I dont know where I did wrong. Thanks for looking into this issue and some suggestions please.

**Comment by javan** [comment]
> The software utility Cron is a time-based job scheduler in Unix-like computer operating systems.

https://en.wikipedia.org/wiki/Cron

**Comment by Sri-K** [comment]
Thanks Javan. So it would not work on windows? For example, If I developed on LINUX and deployed to the windows OS, will it work?

Thanks for your response
