### ISSUE TITLE
Why does whenever converts `2.days.ago` to `172800.ago` in runner string ?

### ISSUE THREAD

**Issue by jarthod** [javan/whenever#579]
I'm not sure if it's a bug or a feature but whenever seems to be converting active support duration to numbers in a runner string ! I have something like that in my `schedule.rb`:
```ruby
every 1.day do
  runner 'Class.method(to: 2.days.ago)'
end
```

And the cron line generated is the following:
`... rails runner -e production '\''Class.method(to: 172800.ago)'\'' ...`

This of course doesn't work and raises `undefined method 'ago' for 172800:Fixnum`

Is whenever doing some weird transformation with the string on purpose ? or is it just a bug ?
Thanks.

**Comment by iCEAGE** [comment]
@jarthod These are related #520 and #530. A [workaround](https://github.com/javan/whenever/issues/520#issuecomment-88287266) for it.

**Comment by jarthod** [comment]
Thanks, yes I already worked around this using `Time.now.advance(days: -2)`
But this is definitely a bug that should be addressed though, and it could prove much more dangerous would the syntax be valid in the end.

**Comment by iCEAGE** [comment]
Yes that's right, I assume whenever parses the file entirely and it shouldn't parse statements inside command, runner and rake statements.

**Comment by jarthod** [comment]
Probably, yes.

**Comment by benlangfeld** [comment]
This was fixed by https://github.com/javan/whenever/pull/587.
