### ISSUE TITLE
Use of Rails minutes with "at:15.minutes" creates invalid cron entry

### ISSUE THREAD

**Issue by JohnB** [javan/whenever#582]
This may be similar to issue #530 in that it is an interaction between Rails idea of time and whenever's idea of time. To run a task every two hours at 2:15, 4:15... it seemed reasonable to say `every(2.hours, at: 15.minutes)` but cron wouldn't allow that and the only error message said to try running whenever on the command line - which happily said `900 0,2,4,6,8,10,12,14,16,18,20,22 * * *`. Not knowing cron very well, I didn't realize that the `900` should have been in the range of 0 to 59.

I finally switched to `every(2.hours, at: 15)` to get the valid `15 0,2,4,6,8,10,12,14,16,18,20,22 * * *` cron entry, but the mix of Rails `2.hours` with the non-Rails `15` is unintuitive compared to the readability of `15.minutes`.

I can't think of a good solution to this, other than documenting it and maybe throwing an exception if the number of minutes/hours/days becomes nonsensical. In the mean time, this issue might inform others who run into a similar problem.

**Comment by attilahorvath** [comment]
I've submitted a fix for this: https://github.com/javan/whenever/pull/686
