### ISSUE TITLE
Is there a way to redo a task every quarter?

### ISSUE THREAD

**Issue by benweizhu** [javan/whenever#585]
Hi,

Is there a way to redo a task every quarter? 
I see weekly, monthly and yearly. But our application needs to do a job every quarter.

Every 3.months?

Thanks,
Ben

**Comment by javan** [comment]
`every 3.months` will generate a crontab entry with `0 0 1 1,4,7,10 * COMMAND` (Day 1 in Feb, May, Aug, Nov) so if that works for you then you're all set. Otherwise I'd just have the job run every month and let the job decide whether or not to perform based on the current date.

**Comment by gregblass** [comment]
@javan According to the cron documentation:

'* * * 1,3,5,7,9,11 * *              Each minute in January,  March,  May, July, September, and November'

So wouldn't 0 0 1 1,4,7,10 * be Day 1 in Jan, April, July, October?

Just want to make sure I'm not missing something?

I'm trying to do quarters on first first day of Jan, April, July, October...so if so, every 3.months does exactly what i need.
