### ISSUE TITLE
Whenever 0.9.4 generating runner commands with script/runner, which does not exist in Rails 4

### ISSUE THREAD

**Issue by alitivay** [javan/whenever#588]
I am using rails 4.2.3 with whenever 0.9.4 and capistrano 3.1. Everything related to scheduling cron jobs works fine except that I get periodic errors in my cron.log (in production) with the following content:

```
/bin/bash: script/runner: No such file or directory
```

then in my crontab -l I have the following:

```
/bin/bash -l -c 'cd /home/deploy/delight/releases/20150916202925 && script/runner -e production '\''Liab.move_expired'\'' >> /home/deploy/delight/releases/20150916202925/log/cron.log 2>&1'
```

which curiously uses the "script/runner" command, which is no longer available in Rails 4 according to this topic on stackoverflow:

http://stackoverflow.com/questions/19683405/why-is-rails-runner-e-production-not-working

furthermore, I have included the `require 'capistrano/bundler'` in my Capfile, and I expect the generated the cron command to contain something like this:

```
bundle exec rails runner -e production
```

instead of

```
script/runner -e production
```

currently I am thinking about creating a custom job_type that manually generates the required rails runner command, but I think this is an issue worth resolving.

**Comment by alitivay** [comment]
I worked around this by adding a custom runner to the `schedule.rb` file:

```
job_type :custom_runner,  
  "cd :path && bundle exec rails runner -e :environment ':task' :output"

every 5.minutes do
  custom_runner "Liab.move_expired"
end
```

but I am still wondering why would whenever generate the deprecated script/runner command on a rails 4 project?

**Comment by mariowise** [comment]
I'm testing your solution from the console and when I perform the `bundle exec rails runner` part, it throws me the `rails [USAGE]` output.

    $ /bin/bash -l -c 'cd /home/someuser/webapps/myapp/releases/20150921134634 && bundle exec rails runner -e production '\''SomeModel.some_method'\'''

    Usage:
      rails new APP_PATH [options]

    Options:
      -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
                                                             # Default: /home/muebleslopez/.rvm/rubies/ruby-2.2.1/bin/ruby
      -m, [--template=TEMPLATE]                              # Path to some application template (can be a filesystem path or URL)
          [--skip-gemfile], [--no-skip-gemfile]              # Don't create a Gemfile
      -B, [--skip-bundle], [--no-skip-bundle]                # Don't run bundle install
      -G, [--skip-git], [--no-skip-git]                      # Skip .gitignore file
          [--skip-keeps], [--no-skip-keeps]                  # Skip source control .keep files
      -O, [--skip-active-record], [--no-skip-active-record]  # Skip Active Record files
      -V, [--skip-action-view], [--no-skip-action-view]      # Skip Action View files
      -S, [--skip-sprockets], [--no-skip-sprockets]          # Skip Sprockets files
          [--skip-spring], [--no-skip-spring]                # Don't install Spring application preloader
      -d, [--database=DATABASE]                              # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                             # Default: sqlite3
      -j, [--javascript=JAVASCRIPT]                          # Preconfigure for selected JavaScript library
                                                             # Default: jquery
      -J, [--skip-javascript], [--no-skip-javascript]        # Skip JavaScript files
          [--dev], [--no-dev]                                # Setup the application with Gemfile pointing to your Rails checkout
          [--edge], [--no-edge]                              # Setup the application with Gemfile pointing to Rails repository
      -T, [--skip-test-unit], [--no-skip-test-unit]          # Skip Test::Unit files
          [--rc=RC]                                          # Path to file containing extra configuration options for rails command
          [--no-rc], [--no-no-rc]                            # Skip loading of extra configuration options from .railsrc file

    Runtime options:
      -f, [--force]                    # Overwrite files that already exist
      -p, [--pretend], [--no-pretend]  # Run but do not make any changes
      -q, [--quiet], [--no-quiet]      # Suppress status output
      -s, [--skip], [--no-skip]        # Skip files that already exist

    Rails options:
      -h, [--help], [--no-help]        # Show this help message and quit
      -v, [--version], [--no-version]  # Show Rails version number and quit

    Description:
        The 'rails new' command creates a new Rails application with a default
        directory structure and configuration at the path you specify.

        You can specify extra command-line arguments to be used every time
        'rails new' runs in the .railsrc configuration file in your home directory.

        Note that the arguments specified in the .railsrc file don't affect the
        defaults values shown above in this help message.

    Example:
        rails new ~/Code/Ruby/weblog

        This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
        See the README in the newly created application to get going.

What should I do to use the `runner` thing?

**Comment by alitivay** [comment]
Yeah, I had the same problem,

I assume you are running that command on your server, inside your current production directory. And you are using Capistrano 3 for deployment.

In that case, go to your `deploy.rb` file and remove the `bin` directory from the `linked_dirs` option. Then add, commit and push to origin. Now re-deploy your app.

For some reason, capistrano 3 contributors decided to share the `bin` directory among all deployments. The bin directory is also always empty and I cannot imagine why. As a result, when you try to run anything inside the rails environment on your server, such as `rails console` or `rails runner` it does not recognize the rails app and says you need to make a new rails app.

remove `bin` from `linked_dirs` and suddenly you can run the `rails runner` command.

**Comment by alitivay** [comment]
Also I have found that after each deployment, you need to first edit your crontab and remove the entry for the previous release and then run `bundle exec whenever --update-crontab` in your current release directory for the gem to work properly.

**Comment by mariowise** [comment]
Awesome!
Sorry I removed the question because I thought that it may be me using wrong capistrano (which was true xD). But now I believe that it may help others. 
In my case `rails runner` command it was not working and it throws me the `rails usage` output.

Thanks @alitivay !! Now my emails work perfectly.

PD: just with removing the `bin` directory from the `Capfile` then the crontab start working perfectly without the `job_type` work arround. Here are my gem versions:

`rails@4.1.5`
`whenever@0.9.4`

**Comment by alitivay** [comment]
Excellent !

**Comment by williamromero** [comment]
I didn't know why my cronjob wasn't work... But thank you guys, i was scared hahah... Thank you for the great helo. 👍

**Comment by aliahmed922** [comment]
@alitivay You're a champ 🥳
