### ISSUE TITLE
whenever in new project deletes existing cron tasks

### ISSUE THREAD

**Issue by chikyukotei** [javan/whenever#590]
I have already operated cron tasks created by *whenever*.

However, existing cron tasks which *whenever* had created was deleted 
when I updated[`whenever -w`] cron tasks in my new project.

Is this bug?
Or, I cannot use *whenever* in multiple projects on the same server?

**Comment by Electrofenster** [comment]
you should use `whenever --update-crontab`

**Comment by chikyukotei** [comment]
Great! thaks.
