### ISSUE TITLE
whenever scheduled at the incorrect moment

### ISSUE THREAD

**Issue by sandrinr** [javan/whenever#592]
Hi

In our deployment, using capistrano v2 with capinfony, whenever is scheduled as pretty much the first thing, even before bundler is called which leads to a execution failure for every first time deployment.

In the file:
https://github.com/javan/whenever/blob/334cfa01f373006cc032e23907b1777a8ea3f3b0/lib/whenever/capistrano/v2/hooks.rb#L5

Schould this not be 'after "deploy:finalize_update"'?

cheers,
Raffaele

**Comment by pawlik** [comment]
Check your `Capfile`. See if you're explicitly require `capistrano/bundler`. You probably should, and it should be required before `whenever/capistrano`

**Comment by benlangfeld** [comment]
There is a proposed solution for this at https://github.com/javan/whenever/pull/535. Please follow along there.
