### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by mtmcfarl** [javan/whenever#593]
Where do I start looking when updating the crontab takes over 5 minutes via Capistrano?

[8a995b17] 	[write] crontab file updated
INFO [8a995b17] Finished in 301.629 seconds with exit status 0 (successful).

Ruby (ruby 2.2.0p0)
whenever (0.9.4)
rails (4.2.1)

**Comment by mtmcfarl** [comment]
If I issue ```/usr/local/rvm/bin/rvm 2.1.3 do bundle exec whenever --update-crontab portal --set environment=production --roles=app,web,db``` on the server in my projects current directory, the command will take well over 1 minute to execute.  Previously this was a pretty quick task to generate a crontab.  Using 0.9.4 of Whenever, Ruby 2.2.0, Rails 4.2.1.

Thoughts?

**Comment by benlangfeld** [comment]
Did you make any changes to your `schedule.rb` or the rest of your application generally? Could you please provide your `Gemfile`, `Gemfile.lock` and `schedule.rb`?

**Comment by mtmcfarl** [comment]
Below is a link to the files you requested.

[Gemfile, Gemfile.lock and schedule.rb](https://gist.github.com/mtmcfarl/c568eb1319d3e0bd98fdf0256185f430)

**Comment by swapnilchincholkar** [comment]
Why you have  ```sleep 300``` in schedule.rb at line 14?

**Comment by benlangfeld** [comment]
This is the correct answer ^
