### ISSUE TITLE
Is there anyway to set additional environment variables to cron jobs?

### ISSUE THREAD

**Issue by tranvictor** [javan/whenever#594]
The only thing relevant I found is `--set` option of `whenever`, however it doesn't work. With this command
```
whenever --set 'VARIABLE=value'
```
it prints nothing different from `whenever` so I start digging into whenever source code. I found this in `job_list.rb`
```
module Whenever
  class JobList
    attr_reader :roles

    def initialize(options)
      @jobs, @env, @set_variables, @pre_set_variables = {}, {}, {}, {}
```
It seems that @env holds environment variables but there is no option from `whenever` for me to set this. Is this @env a half-baked feature?

P/s: I also tried to hard-coded set @env = { VARIABLE: 'value' } and run `whenever` and it prints out exactly what I wanted.
```
VARIABLE=value

0 0 * * * /bin/bash -l -c 'cd /Users/victor/myapp && bin/rails runner -e production '\''MyClass.run'\'''
```

**Comment by tranvictor** [comment]
I want to bring up more discussion on this, the way of prepending variables at the beginning of cronjob file doesn't work for every system. In `Ubuntu` or `Debian`, `vixie-cron` is used so it works, however in `ArchLinux` or `RedHat`, it doesn't.

**Comment by sysout** [comment]
You can change your schedule.rb is like this:

every 1.day, :at => '5:00 am' do
    if @set_variables.has_key?(:VARIABLE)
        job_type :rake, "cd :path && :environment_variable=:environment VARIABLE=:VARIABLE bundle exec rake :task --silent :output"
    else
        job_type :rake, "cd :path && :environment_variable=:environment bundle exec rake :task --silent :output"
    end 
    rake dosomething
end


Then, pass the environment variable through whenever command.
whenever --set 'VARIABLE=value'

**Comment by benlangfeld** [comment]
The above solution satisfies this ticket.

**Comment by vzamanillo** [comment]
I know this issue is too old, but I'm confused about how to pass a custom dynamic environment variables to scheduled rake task, an example:

```
every 1.day, at: '00:30 am', roles: [:db] do 
  rake "PG_DUMP_FILE=daily-#{Time.now.strftime('%Y%m%d%H%M%S')}.backup pg_backup:dump:create" 
end
```

I was reading the wiki, https://github.com/javan/whenever/wiki/Setting-variables-on-the-fly, but I am a bit lost about how to use `set` (or `env`) in my schedule, and if this is really possible.

```
env 'PG_DUMP_FILE', "daily-#{Time.now.strftime('%Y%m%d%H%M%S')}.backup" # should interpolation work?

every 1.day, at: '00:30 am', roles: [:db] do 
  rake "pg_backup:dump:create" 
end
```
Any help would be appreciated, thanks.

**Comment by chase439** [comment]
I was able to pass an environment variable to a rake task like so:

````
every 1.day, at: '00:30 am' do 
  rake "pg_backup:dump:create PG_DUMP_FILE=daily.backup" 
end
````
