### ISSUE TITLE
Rake Arguments

### ISSUE THREAD

**Issue by ben-av** [javan/whenever#597]
Hi,

I'm trying to send an argument to rake using square brackets(as mentioned here: https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task).

Whenever seems to ignore the task when there are brackets

For example  
rake 'tweets:send'  - written to crontab
rake 'tweets:send[cpytel]' - not written to crontab.

Any workaround?

Thanks!

**Comment by benlangfeld** [comment]
The above commit verifies the absence of this bug. If you can reproduce this on the master branch, please provide more details (schedule.rb, `whenever` output, etc) to demonstrate it.
