### ISSUE TITLE
limit maximum number of tasks in whenever gem rails

### ISSUE THREAD

**Issue by wonderer007** [javan/whenever#600]
How can i limit maximum number of tasks in whenever. For example if i have something like this

every 1.hours do
  runner "MyModel.some_process"
  rake "my:rake:task"
  command "/usr/bin/my_great_command"
end

I want to limit it to 1 means if there is a thread already running do not start new thread at next hour.

**Comment by benlangfeld** [comment]
The general idea in https://github.com/javan/whenever/pull/598 is what you're looking for. This is something that cron itself doesn't support, and I believe to be outside the scope of Whenever. You might want to consider using cron or sidekiq-scheduler to schedule jobs on a queue with a single worker.
