### ISSUE TITLE
Use project's ruby version selected by rvm

### ISSUE THREAD

**Issue by Varentsov** [javan/whenever#601]
In my project in file 'script/rails' written 
````ruby
#!/usr/bin/env ruby1.9.1
````
So runner fail's with something like that 
````
Your Ruby version is 1.9.3, but your Gemfile specified 2.1.2
````
But Its can be solved with calling 'ruby' before 'script/rails'
````ruby
job_type :correct_runner, "cd :path && ruby script/rails runner -e :environment ':task' :output"
````

**Comment by j6s** [comment]
Keep in mind not all the scripts found in the scripts folder are written in ruby. This solution would break for every executable that is not ruby based

**Comment by MatthiasWinkelmann** [comment]
You can probably define your own job type. Example:

```ruby
job_type :with_local_ruby, 
    ":environment_variable=:environment rvm in :path do bundle exec ruby :task --silent :output"

every 1.day, :at => '3:30 am' do
  with_local_ruby "-v"
end
```

**Comment by Varentsov** [comment]
Thank you, guys. I think it's also can be solved by not specify ruby version in heading, like this
````
#!/usr/bin/env ruby
````
So ruby should be selected by rvm
