### ISSUE TITLE
Leap year error

### ISSUE THREAD

**Issue by alexbel** [javan/whenever#608]
```ruby
every :week, at: '8:00', roles: [:db] do
  rake 'my_task'
end
```
generates
```bash
0 8 1,8,15,22 * * /bin/bash -l -c 'cd /srv/my_project/releases/20160226220110 && RAILS_ENV=production bundle exec rake my_task --silent'
```
whenever version = 0.9.4

**Comment by javan** [comment]
What's the error?

**Comment by alexbel** [comment]
I should generate `0 8 1,8,15,22, 29 * *`. no?

**Comment by javan** [comment]
If it ran on `29` (or any day close to the end of the month) then the next run on `1` would only be a few days later. So no, it's correct as-is. If you want more even spacing you could specify a day of the week, e.g. `every :sunday`.

**Comment by alexbel** [comment]
Thanks for your help, Javan!
