### ISSUE TITLE
crontab seems to work as root 

### ISSUE THREAD

**Issue by hendranata** [javan/whenever#622]
helo

i face this problem.
when i generate schedule using whenever.

and i use a simple script like this:
* * * * * /bin/bash -l -c 'cd /home/hendranata && ruby -v >> log/test.log 2>&1'

the result in the test.log is:
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

this ruby 1.9 version is actually comming from root user..
and the crontab was set from hendranata user.
but why the cronjob run as a root since i have set the crontab from hendranata user.

and i tried one more time.. i run this script from my terminal:
/bin/bash -l -c 'cd /home/hendranata && ruby -v >> log/test.log 2>&1'

the test.log shows that:
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux] <-- this is correct

it seems that when cronjob running is not load the RVM or ruby environment..
i am not really sure what happen but help me find out this
thanks

**Comment by benlangfeld** [comment]
How did you setup RVM? The reason we use `bash -l` is precisely to load RVM in the job, but it does indeed appear to be failing here, and it may depend on how you setup RVM.

**Comment by hendranata** [comment]
Done already

I just type rvm cron setup

And it will add some scripts to load rvm environment.
Thanks
