### ISSUE TITLE
capistrano: Not run in production

### ISSUE THREAD

**Issue by paulmenzel** [javan/whenever#628]
With whenever 0.9.3, only putting `whenever/capistrano` in `Capfile`, as below, the following happens.

`cap staging deploy` runs the task `whenever/capistrano`, but `cap production deploy` does not. `config/schedule.rb` does not use any environment specific code.

``` ruby
# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require 'capistrano/deploy'

# Includes tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#
require 'capistrano/rvm'
# require 'capistrano/rbenv'
# require 'capistrano/chruby'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/puma'
require 'whenever/capistrano'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

**Comment by benlangfeld** [comment]
Could you please provide the rest of your deployment config and `--trace` output from both deployments?

**Comment by paulmenzel** [comment]
Note, staging was deployed before production.

When running `bundle exec cap production whenever:update_crontab` the crontab is not updated and still the staging commands are in there. Same with `whenever:clear_crontab`.

When running `bundle exec whenever --write RAILS_ENV=production` directly from the deployed directory, it works. (The crontab is overwritten.)

**Comment by benlangfeld** [comment]
> still the staging commands are in there

What does this mean? Without seeing real output it's difficult to understand what you're trying to relay.

**Comment by paulmenzel** [comment]
I meant, that after running it for the production environment, the crontab files should have been overwritten with the comment that the crontab is for the production environment.

```
$ bundle exec cap --trace production whenever:update_crontab
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm:hook (first_time)
** Execute rvm:hook
** Invoke rvm:check (first_time)
** Execute rvm:check
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_rails_env
** Invoke whenever:update_crontab (first_time)
** Execute whenever:update_crontab
$ bundle exec cap --trace staging whenever:update_crontab
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm:hook (first_time)
** Execute rvm:hook
** Invoke rvm:check (first_time)
** Execute rvm:check
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_rails_env
** Invoke whenever:update_crontab (first_time)
** Execute whenever:update_crontab
INFO [dc3f9b78] Running ~/.rvm/bin/rvm jruby-1.7.19 do bundle exec whenever --update-crontab toolbox-staging --set environment=staging --roles=app,web,db as capistrano@localhost
INFO [dc3f9b78] Finished in 9.789 seconds with exit status 0 (successful).
```

So for whatever reason it’s just executed for the staging environment.

**Comment by paulmenzel** [comment]
Capistrano 3.4.1 is used.

**Comment by benlangfeld** [comment]
Can I see your deployment config? It looks like you're deploying both environments to one server and potentially as a single user. That possibly has an impact, but I need to understand the details in their entirety.

**Comment by paulmenzel** [comment]
Do you mean the files `config/deploy.rb` and `config/deploy/*`?

**Comment by benlangfeld** [comment]
Yes.

**Comment by paulmenzel** [comment]
Ok, I’ll try to publish them over the weekend.

Thank you very much for looking into this!

**Comment by ogelacinyc** [comment]
Check and set the roles 
Add code in config/deploy/production.rb
```
p "whenever_roles: #{fetch(:whenever_roles)}" # Remove after checking
set :whenever_roles, -> { [:web, :app, :db, :some_role] }
```
In my case, 'whenever_roles' is only 'db', my production server has a role as 'app'
After adding the role as app, It works to me

**Comment by hopewise** [comment]
I got the same issue, I ended up using:

```
desc "Update crontab with whenever"
    task :update_cron do
      on roles(:app) do
        within current_path do
          execute :bundle, "exec whenever --update-crontab #{fetch(:application)}_#{fetch(:stage)} --set environment=#{fetch(:rails_env)} --user #{fetch(:user)}"
        end
      end
    end

    after :finishing, :update_cron
```
