### ISSUE TITLE
Cron function not working

### ISSUE THREAD

**Issue by karthickms** [javan/whenever#629]
Hi All,

I use whenever gem but the cron job is not working for me on ubuntu production server. I used following command for every 2 minutes send the mail

02 * * * * /bin/bash -l -c 'cd /root/peatio/current && RAILS_ENV=production && bundle exec rake dailymail:email_sender --silent'

**Comment by benlangfeld** [comment]
Please define "not working". Without such a definition (include cron logs at least) it is impossible to help you.

**Comment by karthickms** [comment]
Hi,

I have used following code for send mail,
in config/schedule.rb
-----------------------------
every 1.hours do
  rake 'dailymail:email_sender'
end
----------------------------
in lib/tasks/dailymail.rake
-----------------------------------
namespace :dailymail do
  desc "Send email to users"
  task :email_sender => :environment do
  Member.all.each do |members|
    DailyemailMailer.dailymail.deliver
  end
  end
end
------------------------------------------
in app/mailers/dailyemail_mailer.rb
-------------------------------------------
class DailyemailMailer < ActionMailer::Base
  default from: 'support@tradenaira.com'

  def dailymail(member)
        mail to: member.email, subject: 'TradeNAIRA daily rates update'
  end

end
---------------------------------------
When I enter the crontab -l in terminal, list out the follows,

# Begin Whenever generated tasks for: /root/peatio/current/config/schedule.rb
0 * * * * /bin/bash -l -c '/usr/local/rbenv/shims/backup perform -t database_backup'

10 20 * * * /bin/bash -l -c 'cd /root/peatio/current && RAILS_ENV=production bundle exec rake solvency:clean solvency:liability_proof --silent'

02 * * * * /bin/bash -l -c 'cd /root/peatio/current && RAILS_ENV=production && bundle exec rake dailymail:email_sender --silent'

# End Whenever generated tasks for: /root/peatio/current/config/schedule.rb

---------------------------------------------------
What should I do ?

**Comment by benlangfeld** [comment]
Please confirm the following:

1. Does the mailer work if you invoke the rake task manually?
2. Do your other two cron jobs run successfully?
3. What is printed in your application log and/or cron log (`/var/log/cron.log`) at the time the mailer job runs?
4. What happens if you change the schedule to `every :hour do`?

**Comment by karthickms** [comment]
1. If I manually enter the  "bundle exec rake dailymail:email_sender" in terminal. I got mail.
2. This is a existing application. So I am not sure the above two cron is run or not
3. Sorry I dont know where is cron.log but the cron.log is no on /var/log/ 
4. Same as working. when i change to every :hour

Please help me.

**Comment by benlangfeld** [comment]
> So I am not sure the above two cron is run or not

Please find out. I can't help you otherwise.

> Sorry I dont know where is cron.log but the cron.log is no on /var/log/

What OS are you using? Could you perhaps consult its documentation to find your cron log?

**Comment by karthickms** [comment]
I am using Ubuntu server.

And when i enter the "whereis cron.log" in terminal

It should be displays :
cron: /usr/sbin/cron /etc/cron.weekly /etc/cron.monthly /etc/cron.d /etc/cron.hourly /etc/cron.daily /usr/share/man/man8/cron.8.gz

**Comment by benlangfeld** [comment]
You might want to look into explicitly [logging your cron jobs](https://github.com/javan/whenever/wiki/Output-redirection-aka-logging-your-cron-jobs) and [remove the --silent option](https://github.com/javan/whenever/issues/524#issuecomment-221868150) to get more verbose output. Also try looking in `/var/log/syslog` for cron output. I also still need to know if the other two jobs work correctly.

**Comment by swapnilchincholkar** [comment]
Isn't this is code issue?

Looks like, 
```
def dailymail(member) 
  .....
end
```  
accepts member object & you are not passing that one from rake task. Instead having code 
```
Member.all.each do |members|
    DailyemailMailer.dailymail.deliver
end
```
should be
```
Member.all.each do |member|
    DailyemailMailer.dailymail(member).deliver
end
```

Try to look at the logs, you can see the error else execute below on rails console to see the error
```
DailyemailMailer.dailymail.deliver
```

**Comment by karthickms** [comment]
Hi  @benlangfeld,

Yes. I am checked on the your specified path /var/log/syslog. In that my cron is displayed. But mail is not receiving

**Comment by karthickms** [comment]
Hi All,

I am using following line for that in schedule.rb. It's working fine

env :PATH, ENV['PATH']
env :GEM_PATH, ENV['GEM_PATH']

**Comment by Deepikapc** [comment]
Still issue is not solved! after adding path in schedule.rb file
