### ISSUE TITLE
Failure to bundle update from 0.9.4 to 0.9.5

### ISSUE THREAD

**Issue by existent-co-uk** [javan/whenever#630]
My `Gemfile` contains the line

`gem 'whenever', require: false`

My `Gemfile.lock` currently has `whenever` locked at version 0.9.4. I am hitting a problem running `bundle update`:

```
Installing whenever 0.9.5 (was 0.9.4)

Gem::Package::PathError: installing into parent path /home/someone/.gems/gems/capistrano/v3/tasks/whenever.rake of /home/someone/.gems/gems/whenever-0.9.5 is not allowed
```

**Comment by CR4567** [comment]
Hm... same problem hier. I'm on ruby 2.3.1. Tried as the owning user and sudo user... but same result...

**Comment by fwininger** [comment]
Same problem :+1:

**Comment by klappradla** [comment]
For me, updating works on Ruby **2.2.5**, but breaks for Ruby **2.3.0** and **2.3.1**.

**Comment by Agiley** [comment]
Had the same issue, doing `gem update --system` and then `bundle update` solved it for me

**Comment by bnerd** [comment]
Yep, works with gem version 2.6.4.

**Comment by fwininger** [comment]
Confirm it's work with `gem update --system` on ruby *2.3.1*

**Comment by CR4567** [comment]
also fixed it :-)

**Comment by existent-co-uk** [comment]
This was resolved using `sudo gem update --system` for me also.

**Comment by benlangfeld** [comment]
I'm going to call this a Rubygems bug and close this issue.
