### ISSUE TITLE
9.9.5 and 0.9.6 incompatible with sshkit 1.10.0 (capistrano): instance variable @_env not defined

### ISSUE THREAD

**Issue by cgunther** [javan/whenever#634]
It seems the nested `with` blocks introduced in 1714b45de6303c07006e28b94b4d76d66a6f98e9 are not supported in sshkit 1.10.0. It appears to have been fixed in https://github.com/capistrano/sshkit/pull/345 but not released yet.

After running the `whenever:update_crontab` task, the deploy fails with the error:
instance variable @_env not defined

I can confirm that switching to the master branch of sshkit allows me to deploy without error.

I'm not sure if the `with` blocks can be combined, or if the solution is to wait for the next sshkit release, but I wanted to document this incase anyone else runs into the same issue.

**Comment by benlangfeld** [comment]
Damnit, trying to go too fast. Would you mind prepping a pull request which moves the nesting to a Hash merge?

**Comment by jaredbeck** [comment]
Downgrading to 0.9.4 worked for me.

**Comment by shoyan** [comment]
It is a similar matter. https://github.com/javan/whenever/pull/636

**Comment by shoyan** [comment]
For example.

```ruby
[22] pry(main)> require 'sshkit'
[22] pry(main)> include SSHKit::DSL
[22] pry(main)> on ['shoyan@example.com'] do |host|
[22] pry(main)*   with rails_env: :test do
[22] pry(main)*     with rack_env: :test do
[22] pry(main)*       puts capture(:hostname)
[22] pry(main)*     end  
[22] pry(main)*   end  
[22] pry(main)* end  
example.com
NameError: instance variable @_env not defined
from /Users/shoyan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.10.0/lib/sshkit/backends/abstract.rb:91:in `remove_instance_variable'
```

Correctly is this.

```ruby
[24] pry(main)> on ['shoyan@example.com'] do |host|
[24] pry(main)*   with rails_env: :test, rack_env: :test do  
[24] pry(main)*     puts capture(:hostname)      
[24] pry(main)*   end  
[24] pry(main)* end  
example.com
```

**Comment by benlangfeld** [comment]
Could you try out the master branch and let me know if it resolves the problem? If so, I'll release it immediately.

**Comment by boldov** [comment]
master works fine. Thanks.

**Comment by benlangfeld** [comment]
Released in 0.9.7.

**Comment by cgunther** [comment]
0.9.7 works. Thanks for the quick fix!

**Comment by shoyan** [comment]
Thank you very much 😄
