### ISSUE TITLE
How to set the cron to daemons

### ISSUE THREAD

**Issue by karthickms** [javan/whenever#637]
Hi All,

I am using following code for automatically run the daemons command,

in schedule.rb

```ruby
every 5.hours do
  rake 'dailymail:start_mytask'
end
```

dailymail.rake

```ruby
task :start_mytask => :environment do
   %{RAILS_ENV=production bundle exec ./bin/rake daemons:start}
end
```

What should I do? Please help me

**Comment by benlangfeld** [comment]
You havn't included a question here. Please clarify what help you are expecting.

**Comment by karthickms** [comment]
My point is how to automatically start and stop the daemons

**Comment by benlangfeld** [comment]
What daemons? Your question does not make sense because you're the only one who knows your application and what you're trying to achieve. You need to include a lot more background information if anyone is going to help you.

**Comment by karthickms** [comment]
This is a bulk of programs and when we will be start the daemons it's automatically update the price. But sometimes the daemons will not be working. So I will ask for following question

How to execute the following command with crontab

bundle exec rake daemons:start

**Comment by benlangfeld** [comment]
The documentation covers this:

```ruby
every 5.hours do
  rake "daemons:start"
end
```

**Comment by karthickms** [comment]
@benlangfeld ,

Thanks working fine
