### ISSUE TITLE
(Unintended?) interaction with Fixnum#to_s

### ISSUE THREAD

**Issue by henrebotha** [javan/whenever#643]
I'm trying to do `1.to_s.to_sym` in some of my application code.

At first, I forgot to do `to_s`, so I had `1.to_sym`. I got this error:

    NoMethodError: undefined method `to_sym' for 1:Fixnum
    from /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/whenever-0.9.7/lib/whenever/numeric.rb:10:in `method_missing'

I realised my mistake, so I added `to_s`. Then this happened:

    NoMethodError: undefined method `to_underscore_sym' for 1:Fixnum
    from /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/whenever-0.9.7/lib/whenever/numeric.rb:10:in `method_missing'

In my pry console, it works just fine:

    [3] pry(main)> 1.to_s.to_sym
    => :"1"

What's *especially* annoying is that I can't even monkey patch over this! I can do the following...

    module Fixnum
      def to_sym
        to_s.to_sym
      end
    end

...and it will work perfectly, again, in my pry console, but not in my application.

Wtf is going on?!

**Comment by benlangfeld** [comment]
Could you please try upgrading Whenever to the latest release?

**Comment by benlangfeld** [comment]
Sorry, my bad, you are on the latest version. Do you have any further output, perhaps a full stack trace, and maybe details of where you're doing this in your application code?

**Comment by henrebotha** [comment]
Here's a partial stack trace:

    /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/whenever-0.9.7/lib/whenever/numeric.rb:10:in `method_missing'
    /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sbn-0.9.0/lib/net.rb:28:in `block in symbolize_evidence'
    /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sbn-0.9.0/lib/net.rb:27:in `each'
    /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sbn-0.9.0/lib/net.rb:27:in `symbolize_evidence'
    /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sbn-0.9.0/lib/learning.rb:117:in `add_sample_point'
    /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sbn-0.9.0/lib/learning.rb:112:in `block in learn'
    /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sbn-0.9.0/lib/learning.rb:112:in `yield'
    [...truncated...]

It seems the error doesn't lie with you, so my bad. :) I'll close this for now and reopen if I find that it is indeed `whenever`'s fault.
