### ISSUE TITLE
every 1.minute?

### ISSUE THREAD

**Issue by 1c7** [javan/whenever#647]
Can I write every 1.minute?
I didn't see it on any document.

**Comment by benlangfeld** [comment]
Yes

**Comment by 1c7** [comment]
@benlangfeld  Can you put that on document please? Thank you

**Comment by benlangfeld** [comment]
The README is not an exhaustive list, but instead shows the various forms you can use. Of this form, the examples it gives are

```ruby
every 3.hours do
  runner "MyModel.some_process"
  rake "my:rake:task"
  command "/usr/bin/my_great_command"
end

every 1.day, :at => '4:30 am' do
  runner "MyModel.task_to_run_at_four_thirty_in_the_morning"
end
```

It's reasonable to conclude that `1.minute` also works, and infact testing would reveal this. I don't think any documentation changes are necessary here, but if you have a specific suggestion, feel free to submit a PR.

**Comment by 1c7** [comment]
@benlangfeld  understand.

**Comment by 1c7** [comment]
@benlangfeld 
Linux corn I remember it is not support "second"
so every 3.second is impossiable? must do it in some other way?
I am just asking, I don't need this function right now.

**Comment by benlangfeld** [comment]
That is correct, the minimum resolution that cron supports is minutely.
