### ISSUE TITLE
whenever/capistrano not properly setting environment or updating crontab

### ISSUE THREAD

**Issue by RyanVerhey** [javan/whenever#650]
I am trying to set cron jobs when deploying via Capistrano. In my `Capfile`:
``` ruby
...
require "whenever/capistrano"
...
```
In `deploy.rb`:
``` ruby
...
set :whenever_environment, ->{ fetch(:rails_env) }
set :whenever_identifier,  ->{ "#{fetch(:application)}_#{fetch(:stage)}" }
set :whenever_command,     ->{ "cd #{fetch(:release_path)} && bundle exec whenever" }
...
```
in `deploy.rb`:
``` ruby
set :stage, :development
...
role :app, %w{server_name}
role :web, %w{server_name}
role :db,  %w{server_name}
...
set :rails_env, "development"
```
In `schedule.rb`:
``` ruby
set :output, File.join(Whenever.path, "log", "cron.log")

# Runs every hour on the hour between 8AM and 5PM
every 1.day, at: (8..17).map { |hour| "#{hour > 12 ? hour - 12 : hour}:00#{hour >= 12 ? "pm" : "am"}" } do
  rake "task"
end

```

From everything I've read online, the documentation, and even what I've read in [load:defaults](https://github.com/javan/whenever/blob/master/lib/whenever/capistrano/v3/tasks/whenever.rake), is should be all I need to get the cron jobs to update. However, when I run `bundle exec cap development deploy`, the environment is displayed as 'production' and it doesn't update the crontab file. This is the output from Capistrano:
```
 	0 8,9,10,11,12,13,14,15,16,17 * * * /bin/bash -l -c 'cd /path/to/newest/release && RAILS_ENV=production bundle exec rake task --silent >> /path/to/newest/release/log/cron.log 2>&1'

## [message] Above is your schedule file converted to cron syntax; your crontab file was not updated.
## [message] Run `whenever --help' for more options.
```

Am I missing something? Is this a bug?

EDIT: I want to clarify that I am using Rails v4.2.6, Whenever v0.9.7 and Capistrano v3.5

**Comment by benlangfeld** [comment]
You should probably seek assistance through Capistrano support channels; I do not know why the correct value for `:rails_env` is not being used.

**Comment by RyanVerhey** [comment]
OK, I'll do that, thanks. Any idea why the crontab file isn't being updated?

**Comment by benlangfeld** [comment]
> OK, I'll do that, thanks. Any idea why the crontab file isn't being updated?

The incorrect Whenever command is being run; could you provide the full Capistrano output at debug level?

**Comment by RyanVerhey** [comment]
```
INFO [024a4562] Running cd /path/to/newest/release && bundle exec whenever on server-name
DEBUG [024a4562] Command: cd /path/to/newest/release && bundle exec whenever
DEBUG [024a4562] 	0 8,9,10,11,12,13,14,15,16,17 * * * /bin/bash -l -c 'cd /path/to/newest/release && RAILS_ENV=production bundle exec rake task --silent >> /path/to/newest/release/log/cron.log 2>&1'

## [message] Above is your schedule file converted to cron syntax; your crontab file was not updated.
## [message] Run `whenever --help' for more options.
INFO [024a4562] Finished in 0.787 seconds with exit status 0 (successful).
```

**Comment by benlangfeld** [comment]
I think I'd need to be able to dig in to this; are you able to share the full repo (privately?) for me to debug locally?

**Comment by RyanVerhey** [comment]
Unfortunately I am unable to (sorry), but I can send you our Gemfile if you want it. Say the word and I can email it to the address on your profile.

**Comment by benlangfeld** [comment]
The Gemfile won't help a lot. Best of luck with your debugging, let us know if you find the root cause :)

**Comment by RyanVerhey** [comment]
After doing some more debugging, I'm not sure the environment being set correctly is a Capistrano issue. I made a custom task that printed the `:whenever_environment` before `deploy:updating`, and it was `'development'` like it should be. However the debug output still shows `RAILS_ENV=production`.

**Comment by RyanVerhey** [comment]
It seems to be working now. All I did was comment out the `set :whenever_command`, my custom command seemed to break it somehow. I'm not sure if that helps with debugging this

**Comment by vividh** [comment]
If it helps anyone in the future, I just spent half a day facing the same problems.
Fixed it by using the `--set` and `-i` flags. My custom whenever command now looks like this:

```rb
set :whenever_command, -> {
  on roles(:app) do
    within current_path do
      execute :bundle, :exec, "whenever -i #{fetch(:application)}_#{fetch(:rails_env)} --update-crontab #{fetch(:rails_env) == "production" ? "" : "--load-file config/schedule.dev.rb"} --set environment=#{fetch(:rails_env)}"
    end
  end
}
```

This is on whenever version **0.10.0**.
