### ISSUE TITLE
global set :output now working?

### ISSUE THREAD

**Issue by 1c7** [javan/whenever#651]
### config/schedule.rb
```Ruby
every 1.minute do
  command "python ~/Desktop/whe/config/z.py"
end

set :output, {:error => '~/Desktop/z.error.log', :standard => '~/Desktop/z.standard.log'}
```

<br/>
### z.py (~/Desktop/whe/config/z.py)
```Python
import datetime
import os


now  = datetime.datetime.now()
print(now)

# let python write file in a same folder
filename = 'z.log'
__location__ = os.path.realpath( os.path.join(os.getcwd(), os.path.dirname(__file__)) )
filename = os.path.join(__location__, filename)

f = open(filename, 'a+')
f.write('[z]'+str(now))
f.write('\n')

print('zzzzzzzzzzzzzzzzz')
print()
```

__Python script append current time into a file. that's it.__
and output zzzz.. in console  

<br/>
### After whenever --update-crontab, 
run `crontab -l` I get this:
```sh

* * * * * /bin/bash -l -c 'python ~/Desktop/whe/config/z.py'

# End Whenever generated tasks for: /home/a/Desktop/whe/config/schedule.rb

```

<br/>
### Version
```
a@ubuntu:~/Desktop/whe$ gem list | grep whenever
whenever (0.9.7)
```

<br/>
## Why Global set output not working ?
I mean this:
```
set :output, {:error => '~/Desktop/z.error.log', :standard => '~/Desktop/z.standard.log'}
```

The Python part is right, I can get a`z.log` file with a lot of timestamp in it.
but redirect log part is wrong.
there are no file`z.error.log` or `z.standard.log` on my desktop

<br/>
Thanks  :D

btw
```ruby

every 1.minute do
  command "python ~/Desktop/whe/config/w.py", :output => {:error => '~/Desktop/error.log', :standard => '~/Desktop/cron.log'}
end
```
this work. solve my problem.

### I just want know why the global set output not working
it's in document, it should be right.  

:smile:

**Comment by benlangfeld** [comment]
Probably because you put it after your job definition. Put it at the top of the file instead.

**Comment by 1c7** [comment]
@benlangfeld  Thanks, let me try it.

**Comment by 1c7** [comment]
@benlangfeld  you are right
`corntab -l`
this time output

```
* * * * * /bin/bash -l -c 'python ~/Desktop/whe/config/z.py >> ~/Desktop/z.standard.log 2>> ~/Desktop/z.error.log'
```

**Comment by 1c7** [comment]
@benlangfeld  can I modify the wiki? 
write: "you should write this set output above you job"

**Comment by benlangfeld** [comment]
Go for it :)

**Comment by 1c7** [comment]
@benlangfeld  done :)
