### ISSUE TITLE
require 'whenever/capistrano' leaves old crontab on deploy

### ISSUE THREAD

**Issue by dphuang2** [javan/whenever#654]
I am using Capistrano 3.6.0 to deploy and have setup deployment by placing:
`require 'whenever/capistrano'`
in my Capfile.
The issue is that when the whenever:update_crontab task is run when I "cap production deploy":
```
00:15 whenever:update_crontab
      01 ~/.rvm/bin/rvm default do bundle exec whenever --update-crontab PoGoBag --set environment=production --roles=web,app,db
      01 [write] crontab file updated
    ✔ 01 deploy@146.148.43.226 1.102s
```
it leaves behind the old crontab, thus forcing me to login to my server and manually run:
```
crontab -r
whenever -w
```
on every deployment. 

My assumption is that this is because it leaves behind the crontabs from the old releases and when it writes the new crontab, it is being done in the new release, thus leaving a crontab for every release if you do not clear it.

Is there a way to fix this behavior?

**Comment by benlangfeld** [comment]
Please provide your schedule and the resulting duplicated crontab.

**Comment by dphuang2** [comment]
config/schedule.rb:
```
set :output, "#{path}/log/cron.log"

every 1.minute do
  rake 'refresh_data'
end
```

resulting duplicated crontab:
```
# Begin Whenever generated tasks for: /home/deploy/PoGoBag/releases/20160807211810/config/schedule.rb
* * * * * /bin/bash -l -c 'cd /home/deploy/PoGoBag/releases/20160807211810 && RAILS_ENV=production bundle exec rake refresh_data --silent >> /home/deploy/PoGoBag/releases/20160807211810/log/cron.log 2>&1'

# End Whenever generated tasks for: /home/deploy/PoGoBag/releases/20160807211810/config/schedule.rb

# Begin Whenever generated tasks for: PoGoBag
* * * * * /bin/bash -l -c 'cd /home/deploy/PoGoBag/releases/20160807221322 && RAILS_ENV=production bundle exec rake refresh_data --silent >> /home/deploy/PoGoBag/releases/20160807221322/log/cron.log 2>&1'

# End Whenever generated tasks for: PoGoBag
```

**Comment by benlangfeld** [comment]
There are two problems at play here. First, a trivial one; this line:

```ruby
set :output, "#{path}/log/cron.log"
```

This, as you can see, is redundant. You could equally do this:

```ruby
set :output, "log/cron.log"
```

Since your process is already in the release directory, a relative path is sufficient.

This, however, will not solve your issue. You can also see multiple crontab identifiers in the file:

```
# Begin Whenever generated tasks for: /home/deploy/PoGoBag/releases/20160807211810/config/schedule.rb
```

```
# Begin Whenever generated tasks for: PoGoBag
```

This is the reason for the duplication. In the Capistrano output you provided, the identifier is correctly set to `PoGoBag`. One possible explanation is that you did not have this correctly set the first time you generated the crontab, but you state that this problem occurs every time you run capistrano, so it must still be set incorrectly somewhere else.

Could you please do the following:

1. Clear your crontab: `crontab -r`
2. Run Capistrano in debug mode
3. Provide the resulting Capistrano output (all of it, not just a subsection) and the resulting crontab

**Comment by dphuang2** [comment]
Problem solved when changing to 5 minute intervals.

**Comment by benlangfeld** [comment]
Would you mind trying to put it back to 1 minute intervals and confirming the problem returns, @dphuang2? I'm finding it hard to believe that makes a difference.

**Comment by Rajan4436** [comment]
Has anyone got any solid reason to solve this issue? Even i am facing the duplicate issue on every deployment

````
# Begin Whenever generated tasks for: /home/ubuntu/apps/indie_hacks/releases/20201218041807/config/schedule.rb at: 2020-12-18 04:21:10 +0000
0 0,4,8,12,16,20 * * * /bin/bash -l -c 'cd /home/ubuntu/apps/indie_hacks/releases/20201218041807 && bundle exec bin/rails runner -e production '\''TwitterBot.find_tags_and_retweet'\'' >> ../log/cron.log 2>&1'

# End Whenever generated tasks for: /home/ubuntu/apps/indie_hacks/releases/20201218041807/config/schedule.rb at: 2020-12-18 04:21:10 +0000

# Begin Whenever generated tasks for: /home/ubuntu/apps/indie_hacks/releases/20201218054707/config/schedule.rb at: 2020-12-18 05:50:20 +0000
0 0,4,8,12,16,20 * * * /bin/bash -l -c 'cd /home/ubuntu/apps/indie_hacks/releases/20201218054707 && bundle exec bin/rails runner -e production '\''TwitterBot.find_tags_and_retweet'\'' >> ../log/cron.log 2>&1'

# End Whenever generated tasks for: /home/ubuntu/apps/indie_hacks/releases/20201218054707/config/schedule.rb at: 2020-12-18 05:50:20 +0000

# Begin Whenever generated tasks for: /home/ubuntu/apps/indie_hacks/releases/20201218065323/config/schedule.rb at: 2020-12-18 06:55:56 +0000
0 0,4,8,12,16,20 * * * /bin/bash -l -c 'cd /home/ubuntu/apps/indie_hacks/releases/20201218065323 && bundle exec bin/rails runner -e production '\''TwitterBot.find_tags_and_retweet'\'' >> ../log/cron.log 2>&1'

# End Whenever generated tasks for: /home/ubuntu/apps/indie_hacks/releases/20201218065323/config/schedule.rb at: 2020-12-18 06:55:56 +0000
````

schedule,rb

````
set :output, "log/cron.log"
set :environment, "production"

every 4.hours do
  runner "TwitterBot.find_tags_and_retweet"
end
````
