### ISSUE TITLE
Whenever gem 'failed to load command: rake'

### ISSUE THREAD

**Issue by Awatatah** [javan/whenever#656]
looking for some help.

I am running a rails app (v3.2.5) with the `whenever` gem (v0.9.7) and `rake` (v11.2.2). I am also doing this in a docker container image `ruby:2.3` (`cron` was installed and `bundle install` was ran)

Here is my `schedule.rb`

    set :environment, ENV['RAILS_ENV']

    every '*/2 9,10,11,12,13,14,15,16 * * 1-5' do
	    rake "import_csv", output: {:error => 'log/import_csv_errors.log', :standard => 'log/import_csv.log'}'
    end

*note* `RAILS_ENV` is set at container launch to `development`

Here is my cron job that is on the container after build (`crontab -l`):

    # Begin Whenever generated tasks for: /usr/src/app/config/schedule.rb
    */2 9,10,11,12,13,14,15,16 * * 1-5 /bin/bash -l -c 'cd /usr/src/app && RAILS_ENV=development bundle exec rake import_csv --silent >> log/import_csv.log 2>> log/import_csv_errors.log'

    # End Whenever generated tasks for: /usr/src/app/config/schedule.rb

When this cron job runs, the logs return:

**import_csv_errors.log**

    Bundler::GemNotFound: Could not find rake-11.2.2 in any of the sources
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materialize'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `specs_for'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requested_specs'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requested_specs'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**import_csv.log**

    bundler: failed to load command: rake (/usr/local/bin/rake)

Now here is the odd thing. If I copy the cron job command: 

    /bin/bash -l -c 'cd /usr/src/app && RAILS_ENV=development bundle exec rake import_csv --silent >> log/import_csv.log 2>> log/import_csv_errors.log'

and run this in the container, it works fine, but if the cron job runs it, I get thos errors in the logs!!! I am at a lost here...

I've tried adding 

    env :PATH, ENV['PATH']
    env :GEM_PATH, '/usr/local/bundle'

to the top of `schedule.rb` and I tried doing

    command 'cd /usr/src/app && RAILS_ENV=development bundle exec rake import_csv --silent >> log/import_csv.log 2>> log/import_csv_errors.log'

Instead of using `rake` in the task and I get the same errors..

Any help is appriciated

**Comment by benlangfeld** [comment]
How did you install Ruby?

**Comment by Awatatah** [comment]
Ruby was installed with the image - Ruby 2.3 (Docker hub)

**Comment by Awatatah** [comment]
In case you need it:
**Ruby**
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
**Rails**
Rails 3.2.5
**OS** 
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie
**Kernel**
 Linux 3.13.0-74-generic x86_64

**Comment by joe11051105** [comment]
+1 me too

**Comment by joe11051105** [comment]
I fix this bug, there are two reasons

+ docker ruby 2. 3 image reinstall bundler，see this [issue](https://github.com/docker-library/ruby/issues/73#issuecomment-215095772) 
+ setting ```ENV.each { |k, v| env(k, v) }``` in your `config/schedule.rb`, see this [blogs](https://support.aptible.com/topics/paas/how-to-use-whenever/)

**Comment by Awatatah** [comment]
I was also able to resolve by using a Ubuntu image instead. Here is partially my Dockerfile incase anyone wants to use my method:

`FROM ubuntu:15.10`
`# Installs needed to run rails on ubuntu`
`RUN apt-get update && apt-get install -y apache2 curl git build-essential libmysqlclient-dev mysql-server-5.6 nodejs make`
`RUN apt-get update && apt-get install -y ruby-dev zlib1g-dev`
`RUN gem install rails --version 3.2.5 --no-ri --no-rdoc`

**Comment by againer** [comment]
@joe11051105
"- setting ENV.each { |k, v| env(k, v) } in your config/schedule.rb, see this blogs"

my savior

**Comment by mysterytree** [comment]
@joe11051105 
I follow the blog and get the error
```
"-":36: bad minute
crontab: errors in crontab file, can't install
[fail] Couldn't write crontab; try running `whenever' with no options to ensure your schedule file is valid.
```

**Comment by goetzc** [comment]
@mysterytree Might have been caused by using the `0/1` syntax, try using `*/1` instead.

**Comment by luis-allan** [comment]
> @joe11051105
> I follow the blog and get the error
> 
> ```
> "-":36: bad minute
> crontab: errors in crontab file, can't install
> [fail] Couldn't write crontab; try running `whenever' with no options to ensure your schedule file is valid.
> ```

use whenever with no option, check whether there is a multi-line config or env in output crontab file.

**Comment by palidanx** [comment]
I know this is an old issue, but this fixed it for me, by adding this on top of my crontab file before calling items

```
GEM_HOME=/usr/local/bundle
RACK_ENV=production
BUNDLE_APP_CONFIG=/usr/local/bundle
BUNDLE_BIN=/usr/local/bundle/bin
RAILS_ENV=production
BUNDLE_PATH=/usr/local/bundle
```

**Comment by bholzer** [comment]
@luis-allan 

`use whenever with no option, check whether there is a multi-line config or env in output crontab file.`

This is my problem. I have an environment variable with multiple lines that is breaking whenever. I need this variable, so what are my options?

**Comment by marcoschicote** [comment]
> I fix this issue, there are two reasons
> 
> * docker ruby 2. 3 image reinstall bundler，see this [issue](https://github.com/docker-library/ruby/issues/73#issuecomment-215095772)
> * setting `ENV.each { |k, v| env(k, v) }` in your `config/schedule.rb`, see this [blogs](https://support.aptible.com/topics/paas/how-to-use-whenever/)

This solved a hard issue for me. I would definitely include this in the main page for the docs.
