### ISSUE TITLE
Simple Job Not Working

### ISSUE THREAD

**Issue by LizBayardelle** [javan/whenever#659]
I have a very simple task in my `schedule.rb` file, but it doesn't seem to be functioning.  I have:

```
every 5.minutes do
  redirect_to new_man_test_path
end
```

Yet nothing happens.  I followed the installation instructions exactly how they were listed on the `readme`.  Any ideas why nothing is happening?

**Comment by benlangfeld** [comment]
What exactly do you expect this to do?

**Comment by LizBayardelle** [comment]
Just redirect the user to a certain page every five minutes.

**Comment by prasadsurase** [comment]
@LizBayardelle The schedule.rb file is used to update the crontab with the jobs listed in the file. The crontab list the jobs that need to be executed on the server at specific times(and, at specific intervals). These jobs aren't rails logged-in user specific. This has to be done through the rails app on the server side.
