### ISSUE TITLE
Whenever taking 'production' environment during local development.

### ISSUE THREAD

**Issue by prasadsurase** [javan/whenever#660]
I am using whenever(0.9.7) with rails(4.2.5.2) and ruby(2.3.0). Whenever I update the crontab using whenever, the RAILS_ENV is set to production which actually should be development since my application is running in the development env. Is this a bug or an expected behaviour?

``` cmd
$ crontab -l
crontab: no crontab for prasad
$ whenever --update-crontab
$ crontab -l
# Begin Whenever generated tasks for: /Users/prasad/myproject/config/schedule.rb
0 0 * * * /bin/bash -l -c 'cd /Users/prasad/myproject && RAILS_ENV=production bundle exec rake fetch_data:get_some_data --silent >> /home/deploy/projects/myproject/current/cron_log.log 2>&1'

$ crontab -r
$ crontab -l
crontab: no crontab for prasad
$ whenever --update-crontab --set environment=development
[write] crontab file updated
$ crontab -l
# Begin Whenever generated tasks for: /Users/prasad/myproject/config/schedule.rb
0 0 * * * /bin/bash -l -c 'cd /Users/prasad/myproject && RAILS_ENV=development bundle exec rake fetch_data:get_some_data --silent >> /home/deploy/projects/myproject/current/cron_log.log 2>&1'
```

**Comment by benlangfeld** [comment]
Your pasted logs show this working. What's the problem?

**Comment by vcavallo** [comment]
It looks like the issue @prasadsurase is bringing up is that without explicitly passing in `--set environment=development`, the environment defaults to production. I realize that's the documented behavior, but if I'm understanding correctly, @prasadsurase thinks `whenever` should use development when "in development" (similar to how `rails s` works by default).

**Comment by unikitty37** [comment]
This is documented in the "Setting variables on the fly" page of the wiki, but *not* in the README — which is otherwise sufficiently comprehensive that most people wouldn't even think to check the wiki. Could it be added?

I'd agree that matching the RAILS_ENV the "whenever" command is running in should be the default, though, rather than always defaulting to "production". Convention over configuration, and all that.

(as an aside, there's a page called "instruction and examples" in the wiki which just consists of "bbbbb" :)

**Comment by benlangfeld** [comment]
@unikitty37 I would accept a PR which includes all wiki content into the README. If you would be willing to prep that, I would appreciate it. I can then deactivate the wiki entirely.

**Comment by benlangfeld** [comment]
I'd also accept a PR which defaults to matching `RAILS_ENV` if anyone has time / inclination to prep that.

**Comment by ziaulrehman40** [comment]
i see an open pr

**Comment by jeremiahlukus** [comment]
@benlangfeld
