### ISSUE TITLE
Please specify a valid ruby command or script path

### ISSUE THREAD

**Issue by vemarav** [javan/whenever#663]
Running via Spring preloader in process 30540
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

**Comment by Aravind99** [comment]
Solution:
  rails app:update:bin

**Comment by degill** [comment]
Sorry for hooking into this issue, but I am facing the same problem.

````
class Challenge
  def self.randomly_create_challenge
    # do stuff
  end
end
````

```
every 1.minute do
  runner "Challenge.randomly_create_challenge"
end
```

```
degill$ whenever --version
Whenever v0.9.7
```

````
degill$ rails -v
Rails 5.0.0.1
````
 
````
degill$ whenever --set environment=development
* * * * * /bin/bash -l -c 'cd *APP_NAME_EDITED_OUT* && bundle exec bin/rails runner -e development '\''Challenge.randomly_create_challenge'\'''
````

````
degill$ rails runner -e development '\''Challenge.randomly_create_challenge'\'''
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.
````
I am on MacOS 10.11.6

**Comment by benlangfeld** [comment]
@degill did you try the solution proposed above?

**Comment by degill** [comment]
Oops, sorry to mention that: Yes, I tried that but it did not work for me.

When I run the following, everything works fine:
´´´
runner -e development 'Challenge.randomly_create_challenge'
´´´

I updated my post.
