### ISSUE TITLE
How to use with chruby

### ISSUE THREAD

**Issue by hector** [javan/whenever#664]
I don't know how to write cron tasks while using chruby in the server. Any help will be welcome :)

I am deploying with Capistrano + bundler + chruby.

This configuration results in commands like this:
```
/usr/local/bin/chruby-exec ruby-2.3.1 -- bundle install --path /var/www/my_app/shared/bundle --without development test --deployment --quiet
```

But if set a `schedule.rb`like:
```ruby
every 1.month do
  rake 'maintenance'
end
```

This cron is produced:
```
0 0 1 * * /bin/bash -l -c 'cd /var/www/my_app/releases/20160929093412 && RAILS_ENV=production bundle exec rake maintenance --silent'
```

**Comment by hector** [comment]
I found the following link in chruby wiki, but this solution involves writing variables (like PATH) that I don't know how to set from whenever.
https://github.com/postmodern/chruby/wiki/Cron

**Comment by benlangfeld** [comment]
You could try setting the `:job_template` to something similar to the `chruby-exec` command you mentioned.

**Comment by hector** [comment]
Here is my solution:

schedule.rb
```Ruby
# Change job types that execute ruby to use Chruby
chruby_version = 'ruby-2.3.1'
chruby_bin = '/usr/local/bin/chruby-exec'
chruby_cmd = "#{chruby_bin} #{chruby_version} --"
job_type :rake,    "cd :path && #{chruby_cmd} :environment_variable=:environment bundle exec rake :task --silent :output"
job_type :runner,  "cd :path && #{chruby_cmd} bin/rails runner -e :environment ':task' :output"
job_type :script,  "cd :path && #{chruby_cmd} :environment_variable=:environment bundle exec script/:task :output"

every 1.month do
  rake 'maintenance'
end
```

Two observations here:

- @benlangfeld It is best to only change those job types that use ruby, by changing job_template you will also be changing any task that does not run ruby
- Only changing schedule.rb does not work since cron cannot find chruby. Step below is required.

Add this to the beginning of your cron file (you can `crontab -e`to edit your user's cron file):
```
SHELL=/bin/bash
HOME=/home/deploy
PATH=/bin:/usr/bin:/usr/local/bin
```

This task could be easily automated (with Capistrano, for example) to run on server setup with this shell command:
```bash
printf "SHELL=/bin/bash\nHOME=/home/deploy\nPATH=/bin:/usr/bin:/usr/local/bin\n\n" | crontab
# or if you want to preserve the content already present in crontab
{ crontab -l; printf "SHELL=/bin/bash\nHOME=/home/deploy\nPATH=/bin:/usr/bin:/usr/local/bin\n\n"; }  | crontab
```

I consider this to be more of a workaround. It would be great that whenever, since it already integrates with capistrano, automatically detects if gems like capistrano/chruby, capistrano/bundler, etc. are installed and modify the job templates accordingly.
