### ISSUE TITLE
Started, but will not run CRON tasks.

### ISSUE THREAD

**Issue by afuno** [javan/whenever#667]
Your gem generates a line like this:

```
13,26,39,52 * * * * /bin/bash -l -c 'cd /home/user_name/rails && RAILS_ENV=production bundle exec rake namespace:task --silent'
```

After moving to DigitalOcean I am having a problem with that. CRON task seems and is launched, but Rails task - no.

The solution is to replace the line above on this:
```
13,26,39,52 * * * * cd /home/user_name/application && /home/user_name/.rbenv/shims/rake RAILS_ENV=production namespace:task
```

What could be the problem? Now to me your gem is useless, because I write everything by hand.

**Comment by benlangfeld** [comment]
See the notes in the README which explain how to customise job templates: https://github.com/javan/whenever#define-your-own-job-types

**Comment by afuno** [comment]
@benlangfeld thank you.
