### ISSUE TITLE
Make date string parsing with Chronic configurable

### ISSUE THREAD

**Issue by codener** [javan/whenever#668]
Whenever uses `Chronic` to parse time, e.g. in definitions like

```
every :day, at: '3:00' do
  # Run some code
end
```

As a developer from Germany, I'd expect this to run the Cron job at 3am, however, Whenever runs it at 15:00 = 3pm!

I understand this behaviour feels natural for people using the 12 hours clock, but is very unexpected for people using the 24 hours clock.

I found that [Chronic is configurable](https://github.com/mojombo/chronic/blob/master/lib/chronic/parser.rb) to use 24 hours and some other  useful things. Unfortunately, [Whenever does not allow to configure the Chronic parser](https://github.com/javan/whenever/blob/c7675c81d34131f7107b2930c207c9b994895a08/lib/whenever/cron.rb#L15).

Would you accept a PR that adds Chronic configuration support?

**Comment by benlangfeld** [comment]
> Would you accept a PR that adds Chronic configuration support?

Yes 👍

**Comment by codener** [comment]
Ok, this issue is not urgent to me any more. I will look into it if I should need it again one day.

**Comment by prasadsurase** [comment]
Cronic is being used to parse only the `at` argument. Setting up a parser to parse a single argument is too much specifically when the same results can be achieved by specifying the meridiem as a part of the argument. In the above case, `at: '3:00am'` will work perfectly fine.

**Comment by benlangfeld** [comment]
Too much in what sense @prasadsurase? The parser is already in use, the request here was to expose its configuration.

**Comment by prasadsurase** [comment]
@benlangfeld I meant the overhead of adding the feature where we allow the user to configure the parser as per 12/24 hrs configuration for a single argument(`at`, in the current case). IMO, if we can manage multiple arguments by the same parser, then it would be sensible. We can already achieve the same results by specifying the meridiem in the argument by simpler code.

**Comment by benlangfeld** [comment]
I remain in favour in principle of a feature to configure chronic. Let's discuss the tradeoffs of a possible solution when a PR for it lands and not get ahead of ourselves by discouraging people from contributing.

**Comment by attilahorvath** [comment]
There hasn't been any activity on this in the meantime, so I took it up myself and put up a PR for: https://github.com/javan/whenever/pull/687.
