### ISSUE TITLE
How can I use whenever without capistrano

### ISSUE THREAD

**Issue by wjqwsp** [javan/whenever#669]
I want to know how can I update crontab without capistrano or other deployment tools.I'm in a big ruby on rails project and  it's impossible for me to determine how it deploy.In fact,the project is so mature that the packaging and deployment process are quite complicated and I don't have any rights to modify them.However,I need to do some cron job on the deployment server to support some new functions in the project.Can I do this with whenever?It's fine to update the crontab in my development environment. How can I update the crontab without capistrano on my deployment server?

**Comment by benlangfeld** [comment]
Yes you can do this; the Capistrano support is totally tangential to core operation. Run `bundle execute whenever --help` to see the options available and check out the README. Let us know if you have more specific questions.

**Comment by wjqwsp** [comment]
Do you mean I should run the whenever command on my deployment server to update my crontab?It keeps saying 'command not found'

**Comment by wjqwsp** [comment]
@benlangfeld

**Comment by benlangfeld** [comment]
Within the context of your rails app, the same way you would run a rake command, for example.
