### ISSUE TITLE
# Begin Whenever generated tasks for: /home/ issue

### ISSUE THREAD

**Issue by hendranata** [javan/whenever#671]
helo

i know when i type: whenever --update-crontab
they will write something like this:
# Begin Whenever generated tasks for: /home/xxx.xxx.xxx

but when i integrate whenever with capistrano..
they write different way..
# Begin Whenever generated tasks for: application_name

so that it will generate 2 different crontab..

how to avoid that?

**Comment by benlangfeld** [comment]
Execute `whenever --update-crontab application_name` instead.
