### ISSUE TITLE
Whenever exception notification

### ISSUE THREAD

**Issue by Startouf** [javan/whenever#672]
Is there some support for using Whenever with the Exception notification gem ? Or something similar ? 
My schedules keep crashing for many reasons (constant not autoloaded properly, etc.) and I'm a little bit in the black because of the absence of notifications (Exception Notifier would normally tell me everything that's wrong)

I was wondering if you had either some best practices to share or if it is possible to add an exception notifier integration ? I recently had to use [this guy](https://github.com/h3poteto/exception_notification-shoryuken) to enable notifications on shoryuken workers, and I'm hoping it's possible to have it also for whenever ?

**Comment by benlangfeld** [comment]
If your scheduled jobs boot your rails app then whatever exception notification you have setup there is used. This is not something that falls under the responsibility of Whenever, but is in fact a concern of your application. If you have notes on how to get this set up, a blog post or even a contribution to the Whenever readme would be appropriate.
