### ISSUE TITLE
Cronjobs doesn't run on staging - but works on production.

### ISSUE THREAD

**Issue by manojmj92** [javan/whenever#680]
I am facing a very weird scenario.

I am using whenever to run cron jobs in the following way
```
every 1.day, at: '12:30 am' do
    runner 'CronJobs.some_method'
end
```
The error is logged to `cron_error.log`. Everytime I get this weird error in the log file
`unknown OID 705: failed to recognize type of 'user'. It will be treated as String.`

However, the same cron works fine in the production environment.

I also tried running the method via rails runner and it works fine. Any help will be appreciated.

**Comment by p8** [comment]
@manojmj92 As it's working on production it's probably not a whenever issue. You might want to post this on Stackoverflow.
This might solve your problem: https://gist.github.com/otobrglez/6bc6c4f1c27abb8d1f53

**Comment by manojmj92** [comment]
I finally realised that it was an issue with the linux machine I was running whenever on. It had very low RAM and probably runner couldn't boot up. Fixed this by moving to a bigger instance size.
Also, this error is just a warning and won't stop execution.
