### ISSUE TITLE
Feature to turn off jobs in environment?

### ISSUE THREAD

**Issue by mehulkar** [javan/whenever#682]
Is there a way to turn off a feature in a specific environment?

I'm guessing I can do something like this:

```ruby
if ENV['RAILS_ENV'] == 'production'
  every 5.minutes {}
end
```

But would it make sense to add a more firsthand feature for this? For example:

```ruby
every 5.minutes do
  runner 'soemthing', enable_in_env: ['production']
end
```

**Comment by benlangfeld** [comment]
You would use `@environment`. I would accept a PR which mirrors the `roles:` guard.

**Comment by mehulkar** [comment]
hmm ok. my job type is a rake task, i'm going to implement a config there based on an environment variable. Realized that that's what I want anyway (since my staging and prod servers are both configured as "production" environments anyway. Thanks for the speedy response!
