### ISSUE TITLE
'JAN' or 'Jan' month formats don't work (with capistrano?)

### ISSUE THREAD

**Issue by gregblass** [javan/whenever#694]
I'm going off the cron syntax formatting documentation found [here](http://www.nncron.ru/help/EN/working/cron-format.htm): 

`59 23 31 DEC Fri *` or `* * * Jan,Feb,Mar * *`

Both are causing Capistrano to fail on my production server:

`The deploy has failed with an error: Exception while executing as deployer@ip-add-re-ss: bundle exit status: 1
bundle stdout: bundler: failed to load command: whenever (/home/deployer/apps/derp/shared/bundle/ruby/2.4.0/bin/whenever)
bundle stderr: ArgumentError: Couldn't parse: 0 0 1 JAN *`

Not sure if its an issue with the Capistrano integration, or if this is a known issue in general - or if there are different types of cron formats - but if 3-letter month formats don't work, letting people know in the documentation would be helpful.

**Comment by benlangfeld** [comment]
nncron is a clone of cron and adds things like these alpha days/months. This is not a standard cron feature and Whenever does not contemplate such non-standard extensions to cron.

**Comment by gregblass** [comment]
Gotcha. Thanks for clarifying! I figured it must be something like that.
