### ISSUE TITLE
Error when use whenever in Docker

### ISSUE THREAD

**Issue by slava-nikulin** [javan/whenever#698]
I'm using `ruby:2.4-slim` as base for my rails project, here is my `schedule.rb`:
```
require 'rails'
require 'pathname'

ERROR_LOG_PATH = Pathname.new(File.expand_path(File.dirname(__FILE__))).join('..', 'log', 'whenever_errors.log')

every 1.minute do
  rake "some:task", environment: Rails.env, output: {error: ERROR_LOG_PATH}
end
```

`docker-entrypoint.sh` contains:
```
service cron start
whenever -i
```

Here is error message from logs:

```
Bundler::GemNotFound: Could not find concurrent-ruby-1.0.5 in any of the sources
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
container's `crontab -l` output:
`* * * * * /bin/bash -l -c 'cd /my_project && RAILS_ENV=development bundle exec rake some:task--silent 2>> /my_project /log/whenever_errors.log'`

Please, help me to investigate this problem. Thank you

**Comment by slava-nikulin** [comment]
The reason was that I ran `whenever -i` in 3 containers, so that's why there was concurrency conflict, I guess. Once I've updated Dockerfile to run `whenever -i` for one container, the problem was gone.

**Comment by slava-nikulin** [comment]
Sorry, the problem still remains, here is standatrd output:
`bundler: failed to load command: rake (/usr/local/bin/rake)`

**Comment by adamaig** [comment]
This seems like an issue with your application, not with whenever. Maybe StackOverflow or a forum would be a better place for this?

For what it is worth, it looks like you have an environment and pathing issue. When you post elsewhere you'll need to provide a Dockerfile with any additional build steps so someone can replicate the issue.

**Comment by slava-nikulin** [comment]
Nevermind. I've found solution [here](https://github.com/javan/whenever/issues/656#issuecomment-239111064)
