### ISSUE TITLE
multiple crontab entries after --update-crontab

### ISSUE THREAD

**Issue by nikoloutsa** [javan/whenever#705]
Hi i would like to ask if this is the intended behavior of whenever, because it is a bit confusing for me: 

When i run whenever from inside a soft link directory without setting the identifier flag -i , it gets multiple crontab entries if the symlink changes :(   `/app/current -> app/releases/** `
```
config/deploy.rb
"cd '/app/current' && RAILS_ENV=production bundle exec whenever --update-crontab --set 'path=/app/current/'"
```

Since the `app/current` dir  is a symlink then the  crontab file get the default values after each deployment 
```
 # Begin Whenever generated tasks for: /app/releases/1
 # Begin Whenever generated tasks for: /app/releases/2
 # Begin Whenever generated tasks for: /app/releases/3
...etc
```
```
cd /app/current
pwd   : /app/current
pwd -P : /app/releases/**

lib/whenever.rb
Dir.pwd :/app/releases/**
```
what is the point to generate different cron jobs for the same schedule that always exists in the same full path directory `/app/current/config/schedule.rb` ?
in order to have the intended behavior i have to manually set the idintifier to a static string
```
"whenever -i '/app/current' --update-crontab --set 'path=/app/current/'"
```

**Comment by benlangfeld** [comment]
Whenever cannot know that your schedule is at that symlinked path. It could also be at many others. You'll have to set a static identifier.
