### ISSUE TITLE
Push updated package to rubygems

### ISSUE THREAD

**Issue by DRowan99** [javan/whenever#715]
I noticed that the current state of the master branch is not published to https;//rubygems.org.  I discovered this when I tried running `whenever --crontab-command "sudo crontab"` as documented on the master branch and received an `OptionParser::InvalidOption`.  It turns out this functionality is not part of the latest whenever version (0.9.7).

Since it is so common for the master branch to be the latest packaged gem version of a repo, I was a bit confused at first.  Will you package and push a new version of whenever?

**Comment by benlangfeld** [comment]
v0.10.0 was just released: https://github.com/javan/whenever/blob/master/CHANGELOG.md#0100--november-19-2017
