### ISSUE TITLE
New version is unforgiving for trailing spaces

### ISSUE THREAD

**Issue by sandfoxme** [javan/whenever#726]
```
every '47 */6 * * * ' do
  # ...
end
```

produces error `ArgumentError: Couldn't parse: 47 */6 * * *`

My issue was resolved by removing the trailing space manually however it's a backward incompatible change with a misleading error message

**Comment by benlangfeld** [comment]
The backward compatability is something we have to live with until we cut v1.0, but we can do a better job with the error message by calling #inspect on the value so it would read:

`ArgumentError: Couldn't parse: "47 */6 * * * "`

Is this something you would be prepared to submit a PR for?
