### ISSUE TITLE
Permission denied scriptrunner apk

### ISSUE THREAD

**Issue by ISPADESI** [javan/whenever#731]
> `I`

 have an issue, and if you can help me you would be the best hacker! You know ive had an otg cable issue, and i made 2 scripts, after that loaded them to scriptrunner, put the root mark and clicked run, after that he said to me: `an error has occured in sub: main_vv1(java line: 574) java.io.filenotfoundexception:/system/OTG/otg on : open failed:EACCESS (permition denied)`

**Comment by benlangfeld** [comment]
Closing as spam.
