### ISSUE TITLE
Getting error when connect with MySql in nodejs at AWS instance.

### ISSUE THREAD

**Issue by sumitsinghnaruka** [javan/whenever#739]
Hello

Getting error when connecting to MySql in nodejs at AWS instance.

var connection = mysql.createConnection({
host : 'ec2-54-70-121-12.us-west-2.compute.amazonaws.com',
port : '3306',
user : 'root',
password : 'node@123!',
database : 'test'
});

And error is

{ [Error: connect ECONNREFUSED]
code: 'ECONNREFUSED',
errno: 'ECONNREFUSED',
syscall: 'connect',
fatal: true }

**Comment by benlangfeld** [comment]
This is nothing to do with whenever and you know this is the wrong place for this. Once more and it’s a block.
