### ISSUE TITLE
How to do this in whenever

### ISSUE THREAD

**Issue by mech** [javan/whenever#749]
I need to send job on the first Monday of the month, thus my cron is as follow:

```
30 8 1-7 * * [ "$(date '+\%a')" = "Mon" ]
```

Does whenever support such syntax and can it pass through it if it does not understand it?

**Comment by alfie-max** [comment]
Hi @mech 

From the examples given : https://github.com/javan/whenever#example-schedulerb-file

You can specify a raw cron syntax too 
```
every '30 8 1-7 * * [ "$(date '+\%a')" = "Mon" ]' do
  command "echo 'you can use raw cron syntax too'"
end
```

**Comment by mech** [comment]
Wow, I totally missed that example. I keep thinking it uses some Ruby's expressive language like 1.day, :monday, etc. Tks I will try it.
