### ISSUE TITLE
job according to RAILS_ENV

### ISSUE THREAD

**Issue by MarieS1415** [javan/whenever#759]
Hello,

According to the environment I am in, I would like to trigger some jobs and others not. In other words, I would like to do something like this:

```ruby
if ENV['RAILS_ENV']==test
  job_type :rake, "cd ../app && rake :task ENV=test --silent :output"
  set :output, 'log/whenever.log'
  every 2.minute do
    rake "test_batchs:print"
  end
end
```

But it is not working because it does not know ENV['RAILS_ENV'], which sounds weird to me because it knows ENV['PATH'].

It is possible to do something like this? If so, how should it be written?

Thank you for your help!

**Comment by benlangfeld** [comment]
Try this:

```ruby
if @environment == "test"
  job_type :rake, "cd ../app && rake :task ENV=test --silent :output"
  set :output, 'log/whenever.log'
  every 2.minute do
    rake "test_batchs:print"
  end
end
```

**Comment by MarieS1415** [comment]
Indeed the variable @environement is declared, however it is always "production", even though I try running it in a test or a development environment...

**Comment by benlangfeld** [comment]
It reflects the `—environment` you pass to whenever. Check `whenever —help`

**Comment by MarieS1415** [comment]
It worked by using `whenever --set environment=$RAILS_ENV --update-crontab`, thank you!
