### ISSUE TITLE
When will this part of the fix be released as a gem?

### ISSUE THREAD

**Issue by akicho8** [javan/whenever#772]
https://github.com/javan/whenever/blob/81fc0c675c3d8f69a4220f3453c16e3a0d92b8d4/lib/whenever/capistrano/v3/tasks/whenever.rake#L54

Even with the latest whenever 0.10.0, the code is still old.

**Comment by benlangfeld** [comment]
Released in 0.11.0

**Comment by akicho8** [comment]
Thanks! 👍
