### ISSUE TITLE
Cannot load Rails in runner job

### ISSUE THREAD

**Issue by samnissen** [javan/whenever#782]
I have a task that runs another task on a schedule:

```ruby
every 30.minutes do
  runner MyClass.work(log: “#{Rails.root}/log/file.log”)
end
```

This raises uninitialized constant Whenever::Rails

But the documentation says that runner runs rails. So how is Rails not available?
`job_type :runner,  "cd :path && bin/rails runner -e :environment ':task' :output"`

**Comment by benlangfeld** [comment]
Check the docs closely. This must be a string.

**Comment by samnissen** [comment]
Hi @benlangfeld — sorry, what must be a string? The `Rails.root` call? Is my whenever-executed code path required to be dependency free?

**Comment by benlangfeld** [comment]
Did you look at the README?

`runner “Thing.do_something(5)”`
