### ISSUE TITLE
PG::ConnectionBad: FATAL:  role "my_role" does not exist

### ISSUE THREAD

**Issue by yu-coder** [javan/whenever#790]
Hi,
I can run the task which accesses PostgreSQL database using rake command without any error.
`rake "my_namespace:my_task"`

But when I run the task with **whenever**, I am getting **PG::ConnectionBad: FATAL:  role "my_role" does not exist** error.

```
set :output, 'log/whenever.log'
every 1.minute do
  rake "my_namespace:my_task"
end
```

Has anyone had this issue before?

**Comment by benlangfeld** [comment]
Where is my_role defined?

This isn’t a whenever bug so I’m going to close the issue.

**Comment by yu-coder** [comment]
Hi @benlangfeld 
Thanks for reaching out.
I can run the task without creating **my_role** role but when running the task with **whenever** it requires that **my_role** role.
I am not sure why this requires.

**Comment by benlangfeld** [comment]
Because you have configured your application wrong in some way. Grep your source code for my_role

**Comment by yu-coder** [comment]
I just checked with **grep my_role** but nothing was there.
I am just weird since I can the task manually by **rake "my_namespace:my_task"**
And in whenever **schedule.rb**, used this same command.
