### ISSUE TITLE
Documentation missing for logging to output file

### ISSUE THREAD

**Issue by ademars94** [javan/whenever#799]
How do you write to the Whenever log?  You can redirect the output, but how do I actually send the output from my program into Whenever's log file?

A documentation section about this would be helpful.  Once I figure out how to do this I am happy to update the documentation.

**Comment by benlangfeld** [comment]
Whenever has a log file? What are you trying to achieve?

**Comment by ademars94** [comment]
Maybe I've phrased this wrong, but I am talking about sending output from my program to the log file that you specify with `output` in `schedule.rb`

**Comment by benlangfeld** [comment]
Please provide your schedule. The output override is intended to be something like `> my/log.txt`. In this case, stdout is redirected there. You just need your application to print to stdout.

**Comment by ademars94** [comment]
I think this answers my question.  Not sure if this is worth putting into the documentation but thank you for the help.
