### ISSUE TITLE
Job:command not working

### ISSUE THREAD

**Issue by obromios** [javan/whenever#801]
Thank you for a most useful gem.  The rake and runner methods work for me, but not the ```command``` method. I have asked a [question](https://stackoverflow.com/questions/61517862/the-command-method-is-being-ignored-by-the-whenever-scheduling-gem) about this on SO.
In the scheduling file, I have

    #config/schedule.rb
    set :output, "log/cron.log"
    every 1.day, at: '23:00' do
       rake 'util:something'
       runner 'User.something_else'
       command "echo 'I just want to see something happen'"
    end

The rake, and runner methods work fine and I see output in the ```cron.log```. However, there is no output from the command method, it just seems to be ignored. It may be something to do with user permissions, but I am running it from the base directory of my ruby on rails app, so I would have thought I would have the correct permissions.

**Comment by reinvanimschoot** [comment]
I got the same problem.

**Comment by obromios** [comment]
In my case, the problem was that I needed to specify the full path to the log, see my SO[ answer.](https://stackoverflow.com/a/61845268/1299362)
