### ISSUE TITLE
Cron jobs inside a docker container

### ISSUE THREAD

**Issue by spryffee** [javan/whenever#850]
What's a better way to make whenever running tasks with app running inside a docker container? I migrated my deployment to Kamal and Cron tasks do not work anymore. Kamal doc suggests running cron job on specific container with settings stored in config/crontab but this is not what we expect using whenever.

**Comment by Michoels** [comment]
Have you tried adding this to your Dockerfile?

```Dockerfile
RUN bundle exec whenever --update-crontab
```

**Comment by spryffee** [comment]
> Have you tried adding this to your Dockerfile?
> 
> ```dockerfile
> RUN bundle exec whenever --update-crontab
> ```

Unfortunately, It doesn't work
```#20 [stage-2 5/5] RUN bundle exec whenever --update-crontab
#20 0.502 bundler: failed to load command: whenever (/usr/local/bundle/ruby/3.2.0/bin/whenever)
#20 0.502 /usr/local/bundle/ruby/3.2.0/gems/whenever-1.0.0/lib/whenever/command_line.rb:77:in `popen': No such file or directory - crontab (Errno::ENOENT)```

**Comment by Michoels** [comment]
Are you using the ruby-slim or ruby-alpine images?

They may require special configuration to install `cron` properly.
([See here](https://stackoverflow.com/questions/56901751/enable-crond-in-an-alpine-container) or [here](https://gist.github.com/mhubig/a01276e17496e9fd6648cf426d9ceeec) for example)

**Comment by spryffee** [comment]
I'm using standard production Docker file that comes with Rails 7.1. So it's ruby:$RUBY_VERSION-slim

**Comment by nbnp11** [comment]
1. add privileges for your rails user (Dockerfile)
```ruby
....
# Run and own only the runtime files as a non-root user for security
RUN useradd rails --create-home --shell /bin/bash && \
    chmod gu+rw /var/run && \
    chmod gu+s /usr/sbin/cron && \
    chown -R rails:rails db log tmp
...
```

2. add to your entrypoint (default - `bin/docker-entrypoint`)
```ruby
#!/bin/bash -e

touch ./log/cron.log
cron
./bin/bundle exec whenever --update-crontab

./bin/rails db:prepare

exec "${@}"
```
3. add to config/schedule.rb

```ruby
ENV.each { |k, v| env(k, v) }

set :output, 'log/cron.log'
set :environment, ENV['RAILS_ENV']

job_type :runner, "cd :path && bin/rails runner -e :environment ':task' :output"
```

that's what helped me

now you can check if cron is running (`service cron status` in container's bash) and debug jobs output in `log/cron.log`

**Comment by jankeesvw** [comment]
I ran into issues with getting Whenever working from Kamal, I documented the working solution here: https://github.com/basecamp/kamal/issues/480#issuecomment-2322032162
